require("ItemTweaker_Copy_CC");

--AllAmericanApocolypse
--https://steamcommunity.com/sharedfiles/filedetails/?id=2026187681
if getActivatedMods():contains("AAApoc") then
TweakItem("TPaste.TPasteBSoda","DisplayCategory","Cook");
TweakItem("TPaste.TPasteBSodaEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAMeatGrinder","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinMix","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinMixEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAHomemadeGelatin","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAACreamOfTartar","DisplayCategory","FoodN");
TweakItem("AAApoc.AAAMilkPowder","DisplayCategory","Cook");
TweakItem("AAApoc.AAACheesePowder","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAACheeseBlock","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAProcessedPackage","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAATomatoSlices","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAOnionSlices","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPickleSlices","DisplayCategory","FoodN");
-- TweakItem("AAApoc.AAADicedLettuce","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAJarOfPickles","DisplayCategory","FoodN");
-- TweakItem("AAApoc.AAAJarOfPicklesStore","DisplayCategory","FoodN");
-- TweakItem("AAApoc.AAABurgerBun","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABurgerBunPackage","DisplayCategory","FoodP");
TweakItem("AAApoc.AAABurgerBunPan","DisplayCategory","Cook");
TweakItem("AAApoc.AAABurgerBunPanPrepRaw","DisplayCategory","Cook");
TweakItem("AAApoc.AAAFrenchFrySlicer","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAASlicedPotato","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChiliCheeseFries","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABakedFries","DisplayCategory","FoodP");
TweakItem("AAApoc.AAABreadingBowl","DisplayCategory","Cook");
TweakItem("AAApoc.AAABreadingMix","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAADeadChicken","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChickenBreast","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAFriedChickenBreast","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChickenBreastStrips","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChickenTenders","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAVanillaExtract","DisplayCategory","FoodN");
TweakItem("AAApoc.AAAEggBeater","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAHomemadeIcecream","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAIcecreamMelted","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAHeavyCreamPowder","DisplayCategory","Cook");
TweakItem("AAApoc.AAAJarOfHeavyCream","DisplayCategory","Cook");
TweakItem("AAApoc.AAAButterPot","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAHamCheeseSandwich","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGrilledHamCheese","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAHotDogPrep","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAChiliDog","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAChiliDogPrep","DisplayCategory","Cook");
TweakItem("AAApoc.AAAHotDogBunPan","DisplayCategory","Cook");
TweakItem("AAApoc.AAAIntestines","DisplayCategory","Cook");
TweakItem("AAApoc.AAAHotDogCasings","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAHotDogBunPackage","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAHotDogBun","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPackOfHotDogs","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAHotDogLink","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAADillRelish","DisplayCategory","FoodN");
-- TweakItem("AAApoc.AAADillRelishStore","DisplayCategory","FoodN");
TweakItem("AAApoc.AAACheeseGrater","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAADicedOnion","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAShreddedCheese","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAHotDogBunPanPrepRaw","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAToastSlices","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastButterSlices","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABoiledEgg","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAFriedEgg","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAJarOfMilk","DisplayCategory","FoodB");
-- TweakItem("AAApoc.AAAPlainMilkshake","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPlainMilkshakeMugRed","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPlainMilkshakeMugWhite","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPlainMilkshakeMugSpiffo","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshake","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshakeMugRed","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshakeMugWhite","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshakeMugSpiffo","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshake","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshakeMugRed","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshakeMugWhite","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshakeMugSpiffo","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPlainMilkshakeMugBlueMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPlainMilkshakeMugRedMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPlainMilkshakeMugWhiteMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPlainMilkshakeMugSpiffoMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshakeMugBlueMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshakeMugRedMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshakeMugWhiteMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAChocoMilkshakeMugSpiffoMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshakeMugBlueMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshakeMugRedMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshakeMugWhiteMelted","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABerryMilkshakeMugSpiffoMelted","DisplayCategory","FoodP");
TweakItem("AAApoc.AAACreamOfTartarEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAMilkPowderEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAEmptyJar","DisplayCategory","Cont");
TweakItem("AAApoc.AAAHeavyCreamPowderEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAJarOfPicklesEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAABreadingMixEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAVanillaExtractEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAJarOfCherriesEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAWhippedCreamEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAJarOfGJellyEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAJarOfAJellyEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAACoffeeCreamerEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAACookieDoughEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAEmptyMacBox","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxCherryEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxOrangeEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxLemonEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxAppleEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxBerryEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxGrapeEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxPineappleEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxChocolateEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxVanillaEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAGelatinBoxBananaEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAFoodDyesEmpty","DisplayCategory","Junk");
TweakItem("AAApoc.AAAWaffleIron","DisplayCategory","Cook");
TweakItem("AAApoc.AAAPancakeMixHMade","DisplayCategory","Cook");
TweakItem("AAApoc.AAAJarOfCherries","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAWhippedCreamStore","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAWhippedCreamHMade","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAJarOfGJellyStore","DisplayCategory","FoodN");
-- TweakItem("AAApoc.AAAJarOfAJellyStore","DisplayCategory","FoodN");
TweakItem("AAApoc.AAACorndogStick","DisplayCategory","Cook");
TweakItem("AAApoc.AAACornbreadPrep","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAACorndogPrep","DisplayCategory","FoodP");
TweakItem("AAApoc.AAACorndogRaw","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAACWSandwich","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPBJSandwich","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAPBMarmSandwich","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABLTSandwich","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAABananaSplit","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAACoffeeCreamerStore","DisplayCategory","FoodN");
-- TweakItem("AAApoc.AAACoffeeCreamerHMade","DisplayCategory","FoodN");
-- TweakItem("AAApoc.AAACookieDoughStore","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAACookieDoughHMade","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAACookiePan","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAMeatloafSauce","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAMeatloaf","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAMeatloafCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAMeatloafSlice","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAMeatloafSandwich","DisplayCategory","FoodP");
TweakItem("AAApoc.AAACheeseWheelChdr","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAABowlMacCheese","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAEmptyIceTray","DisplayCategory","Container");
TweakItem("AAApoc.AAAFullIceTrayWater","DisplayCategory","FoodB");
TweakItem("AAApoc.AAAFullIceTrayIce","DisplayCategory","FoodB");
TweakItem("AAApoc.AAAIceCube","DisplayCategory","FoodB");
TweakItem("AAApoc.AAAIceCubeMelted","DisplayCategory","FoodB");
TweakItem("AAApoc.AAAPlasticIceBag","DisplayCategory","FoodB");
TweakItem("AAApoc.AAAGelatinBoxCherry","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxOrange","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxLemon","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxApple","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxBerry","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxGrape","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxPineapple","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepCherry","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepOrange","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepLemon","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepApple","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepBerry","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepGrape","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepPineapple","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAGelatinPrepCherryCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinPrepOrangeCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinPrepLemonCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinPrepAppleCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinPrepBerryCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinPrepGrapeCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinPrepPineappleCooked","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinCherryBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinOrangeBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinLemonBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinAppleBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinBerryBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinGrapeBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinPineappleBowl","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAGelatinBoxChocolate","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxVanilla","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinBoxBanana","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepChocolate","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepVanilla","DisplayCategory","Cook");
TweakItem("AAApoc.AAAGelatinPrepBanana","DisplayCategory","Cook");
-- TweakItem("AAApoc.AAAGelatinChocolateBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinVanillaBowl","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAGelatinBananaBowl","DisplayCategory","FoodP");
TweakItem("AAApoc.AAAFoodDyes","DisplayCategory","Junk");
-- TweakItem("AAApoc.AAAToastAJelly","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastGJelly","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastButterGJelly","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastButterAJelly","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastFJam","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastMarmalade","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastButterFJam","DisplayCategory","FoodP");
-- TweakItem("AAApoc.AAAToastButterMarmalade","DisplayCategory","FoodP");
end
