require("ItemTweaker_Copy_CC");

--AMMOCRAFT
--https://steamcommunity.com/sharedfiles/filedetails/?id=2245813444
if getActivatedMods():contains("ammocraft") or getActivatedMods():contains("ammocraftfirearms") then
--Crafting Ammo
TweakItem("Base.Bullets9mm_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets45_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets44_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets38_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.308Bullets_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.223Bullets_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.556Bullets_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.ShotgunShells_casingbox","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets9mm_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets45_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets44_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets38_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.308Bullets_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.223Bullets_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.556Bullets_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.ShotgunShells_tipbox","DisplayCategory","CraftAmmo");
TweakItem("Base.SP_Primers_box","DisplayCategory","CraftAmmo");
TweakItem("Base.LP_Primers_box","DisplayCategory","CraftAmmo");
TweakItem("Base.R_Primers_box","DisplayCategory","CraftAmmo");
TweakItem("Base.SG_Primers_box","DisplayCategory","CraftAmmo");
TweakItem("Base.GunpowderJar","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets9mm_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets9mm_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets9mm_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets9mm_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets45_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets45_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets45_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets45_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets44_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets44_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets44_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets44_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets38_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets38_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets38_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.Bullets38_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.308Bullets_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.308Bullets_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.308Bullets_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.308Bullets_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.223Bullets_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.223Bullets_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.223Bullets_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.223Bullets_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.556Bullets_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.556Bullets_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.556Bullets_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.556Bullets_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.ShotgunShells_casing","DisplayCategory","CraftAmmo");
TweakItem("Base.ShotgunShells_casing_spent","DisplayCategory","CraftAmmo");
TweakItem("Base.ShotgunShells_casing_spent_noprimer","DisplayCategory","CraftAmmo");
TweakItem("Base.ShotgunShells_tip","DisplayCategory","CraftAmmo");
TweakItem("Base.SP_Primers","DisplayCategory","CraftAmmo");
TweakItem("Base.LP_Primers","DisplayCategory","CraftAmmo");
TweakItem("Base.R_Primers","DisplayCategory","CraftAmmo");
TweakItem("Base.SG_Primers","DisplayCategory","CraftAmmo");
TweakItem("Base.SP_Primers_Spent","DisplayCategory","CraftAmmo");
TweakItem("Base.LP_Primers_Spent","DisplayCategory","CraftAmmo");
TweakItem("Base.R_Primers_Spent","DisplayCategory","CraftAmmo");
TweakItem("Base.SG_Primers_Spent","DisplayCategory","CraftAmmo");
TweakItem("Base.45BulletsMold","DisplayCategory","CraftAmmo");
TweakItem("Base.44BulletsMold","DisplayCategory","CraftAmmo");
TweakItem("Base.38BulletsMold","DisplayCategory","CraftAmmo");
TweakItem("Base.556BulletsMold","DisplayCategory","CraftAmmo");
TweakItem("Base.Lead","DisplayCategory","CraftAmmo");
TweakItem("Base.Saltpeter","DisplayCategory","CraftAmmo");
TweakItem("Base.Sulfur","DisplayCategory","CraftAmmo");
--Litature
TweakItem("Base.GunnutMonthly1","DisplayCategory","LitR");
TweakItem("Base.GunnutMonthly2","DisplayCategory","LitR");
TweakItem("Base.GunnutMonthly3","DisplayCategory","LitR");
TweakItem("Base.GunnutMonthly4","DisplayCategory","LitR");
TweakItem("Base.GunnutMonthly5","DisplayCategory","LitR");
TweakItem("Base.GunnutMonthly6","DisplayCategory","LitR");
TweakItem("Base.GunnutBible","DisplayCategory","LitR");
--Tool
TweakItem("Base.Reloadingpress","DisplayCategory","Tool");
TweakItem("Base.Pliers","DisplayCategory","Tool");
end
