require("ItemTweaker_Copy_CC");

--CornerStoreCandiesAndSodas
--https://steamcommunity.com/sharedfiles/filedetails/?id=2412050672
if getActivatedMods():contains("2412050672") then
TweakItem("CCS.Pepso","DisplayCategory","FoodB");
TweakItem("CCS.DrPepppa","DisplayCategory","FoodB");
TweakItem("CCS.FantoOrange","DisplayCategory","FoodB");
TweakItem("CCS.FantoPurple","DisplayCategory","FoodB");
TweakItem("CCS.FantoRed","DisplayCategory","FoodB");
TweakItem("CCS.RootBeer","DisplayCategory","FoodB");
TweakItem("CCS.RedDeath","DisplayCategory","FoodB");
TweakItem("CCS.LemonLime","DisplayCategory","FoodB");
TweakItem("CCS.GingerAle","DisplayCategory","FoodB");
TweakItem("CCS.MootinDiw","DisplayCategory","FoodB");
TweakItem("CCS.MootinDiwQ","DisplayCategory","FoodB");
TweakItem("CCS.YF","DisplayCategory","FoodB");
TweakItem("CCS.RokaCola","DisplayCategory","FoodB");
TweakItem("CCS.Haterade","DisplayCategory","FoodB");
-- TweakItem("CCS.Doritas","DisplayCategory","FoodN");
-- TweakItem("CCS.Leis","DisplayCategory","FoodN");
-- TweakItem("CCS.Tingles","DisplayCategory","FoodN");
-- TweakItem("CCS.TinglesMini","DisplayCategory","FoodN");
-- TweakItem("CCS.Bugles","DisplayCategory","FoodN");
-- TweakItem("CCS.Snackers","DisplayCategory","FoodN");
-- TweakItem("CCS.Leeroy","DisplayCategory","FoodN");
-- TweakItem("CCS.ChitChat","DisplayCategory","FoodN");
-- TweakItem("CCS.SNM","DisplayCategory","FoodN");
-- TweakItem("CCS.Boreal","DisplayCategory","FoodN");
-- TweakItem("CCS.Tittles","DisplayCategory","FoodN");
-- TweakItem("CCS.4muskepeers","DisplayCategory","FoodN");
-- TweakItem("CCS.Coffeechisps","DisplayCategory","FoodN");
-- TweakItem("CCS.Almondjaws","DisplayCategory","FoodN");
-- TweakItem("CCS.ZersheyBar","DisplayCategory","FoodN");
-- TweakItem("CCS.Mounds","DisplayCategory","FoodN");
-- TweakItem("CCS.PayDay","DisplayCategory","FoodN");
-- TweakItem("CCS.CCBlack","DisplayCategory","FoodN");
-- TweakItem("CCS.CCYellow","DisplayCategory","FoodN");
-- TweakItem("CCS.CCPink","DisplayCategory","FoodN");
-- TweakItem("CCS.Kwix","DisplayCategory","FoodN");
-- TweakItem("CCS.RRBlue","DisplayCategory","FoodN");
-- TweakItem("CCS.RRRed","DisplayCategory","FoodN");
-- TweakItem("CCS.RRGreen","DisplayCategory","FoodN");
-- TweakItem("CCS.BagofRollys","DisplayCategory","FoodN");
-- TweakItem("CCS.SweetTreats","DisplayCategory","FoodN");
-- TweakItem("CCS.GumStickRed","DisplayCategory","FoodN");
-- TweakItem("CCS.GumStickBlue","DisplayCategory","FoodN");
-- TweakItem("CCS.GumPackRed","DisplayCategory","FoodN");
-- TweakItem("CCS.GumPackBlue","DisplayCategory","FoodN");
TweakItem("CCS.PepsoCan","DisplayCategory","FoodB");
TweakItem("CCS.DrPeppaCan","DisplayCategory","FoodB");
TweakItem("CCS.FantoGrapeCan","DisplayCategory","FoodB");
TweakItem("CCS.FantoRedCan","DisplayCategory","FoodB");
TweakItem("CCS.FantoOrangeCan","DisplayCategory","FoodB");
TweakItem("CCS.RootBeerCan","DisplayCategory","FoodB");
TweakItem("CCS.RokaColaCan","DisplayCategory","FoodB");
TweakItem("CCS.GingerAleCan","DisplayCategory","FoodB");
TweakItem("CCS.LemonLimeCan","DisplayCategory","FoodB");
TweakItem("CCS.MootinDiwCan","DisplayCategory","FoodB");
TweakItem("CCS.MootinDiwQCan","DisplayCategory","FoodB");
TweakItem("CCS.RCCan","DisplayCategory","FoodB");
TweakItem("CCS.YFCan","DisplayCategory","FoodB");
TweakItem("CCS.HateradeWh","DisplayCategory","FoodB");
TweakItem("CCS.HateradeBl","DisplayCategory","FoodB");
TweakItem("CCS.HateradeYl","DisplayCategory","FoodB");
TweakItem("CCS.minichugBL","DisplayCategory","FoodB");
TweakItem("CCS.minichugPi","DisplayCategory","FoodB");
TweakItem("CCS.minichugOr","DisplayCategory","FoodB");
end
