require("ItemTweaker_Copy_CC");

--NewEkron
--https://steamcommunity.com/sharedfiles/filedetails/?id=2712480036
if getActivatedMods():contains("TheWorkshop(new version)") then
TweakItem("Base.TheBong","DisplayCategory","WepMelee");
TweakItem("Base.Rusty","DisplayCategory","WepFire");
end

--Pitstop
--https://steamcommunity.com/sharedfiles/filedetails/?id=2597946327
if getActivatedMods():contains("Pitstop") or getActivatedMods():contains("PitstopLegacy") then
TweakItem("Base.AirMags_WorldItem","DisplayCategory","Misc");
TweakItem("Base.AstroSpiff_WorldItem","DisplayCategory","Collect");
TweakItem("Base.Bender_WorldItem","DisplayCategory","Collect");
TweakItem("Base.BuckRogersGun","DisplayCategory","WepFire");
TweakItem("Base.HBoard_WorldItem","DisplayCategory","Collect");
TweakItem("Base.Lightsaber_WorldItem","DisplayCategory","Collect");
TweakItem("Base.TheZapper","DisplayCategory","WepFire");
TweakItem("Base.Lightsaber01","DisplayCategory","WepMelee");
TweakItem("Base.Lightsaber02","DisplayCategory","WepMelee");
TweakItem("Base.Lightsaber03","DisplayCategory","WepMelee");
TweakItem("Base.E11Blaster","DisplayCategory","WepFire");
TweakItem("Base.SausageWeapon","DisplayCategory","WepMelee");
TweakItem("Base.M41APulse","DisplayCategory","WepFire");
TweakItem("Base.FutureAssaultRifle","DisplayCategory","WepFire");
TweakItem("Base.MP5HK","DisplayCategory","WepFire");
TweakItem("Base.CyberPistol","DisplayCategory","WepFire");
TweakItem("Base.FutureRevolver","DisplayCategory","WepFire");
TweakItem("Base.Boltgun","DisplayCategory","WepFire");
TweakItem("Base.HoverboardMelee","DisplayCategory","WepMelee");
TweakItem("Base.GhostTrap","DisplayCategory","WepMelee");
TweakItem("Base.EnergySword","DisplayCategory","WepMelee");
TweakItem("Base.DjackzVinyl","DisplayCategory","WepMelee");
TweakItem("Base.FutureShotgun","DisplayCategory","WepFire");
TweakItem("Base.JadeCandyCane","DisplayCategory","WepMelee");
TweakItem("Base.MndoBrush","DisplayCategory","WepMelee");
TweakItem("Base.JeanBeanWand","DisplayCategory","WepMelee");
TweakItem("Base.R2D2_WorldItem","DisplayCategory","Collect");
TweakItem("Base.AirMags","DisplayCategory","ClothFeet");
TweakItem("Base.AlienBackPack","DisplayCategory","ClothBack");
TweakItem("Base.AlienCap","DisplayCategory","ClothHead");
TweakItem("Base.AstroHelmet","DisplayCategory","ClothHead");
TweakItem("Base.AstronautSuit","DisplayCategory","ClothBody");
TweakItem("Base.AstroSuit","DisplayCategory","ClothBody");
TweakItem("Base.Bandshirt","DisplayCategory","ClothBody");
TweakItem("Base.CleanUpKrewJumpsuit","DisplayCategory","ClothBody");
TweakItem("Base.Shoes_CleanUpKrewSneakers","DisplayCategory","ClothFeet");
TweakItem("Base.DarthVaderHelmet","DisplayCategory","ClothHead");
TweakItem("Base.DisrespectMullet","DisplayCategory","Appear");
TweakItem("Base.DisrespectVest","DisplayCategory","ClothBody");
TweakItem("Base.FluxBackPack","DisplayCategory","ClothBack");
TweakItem("Base.FutureJacket","DisplayCategory","ClothBody");
TweakItem("Base.KleanBackPack","DisplayCategory","ClothBack");
TweakItem("Base.MedievalHelmet","DisplayCategory","ClothHead");
TweakItem("Base.PowerArmor","DisplayCategory","ClothBody");
TweakItem("Base.RoboCopHelmet","DisplayCategory","ClothHead");
TweakItem("Base.ScifiHelmet01","DisplayCategory","ClothHead");
TweakItem("Base.SheriffEliBelt","DisplayCategory","ClothBag");
TweakItem("Base.SheriffEliHat","DisplayCategory","ClothHead");
TweakItem("Base.SheriffEliVest","DisplayCategory","ClothBody");
TweakItem("Base.SpaceHelmet","DisplayCategory","ClothHead");
TweakItem("Base.Shirt_StarTrekShirt1","DisplayCategory","ClothBody");
TweakItem("Base.Dress_StarTrekDress1","DisplayCategory","ClothBody");
TweakItem("Base.StormTrooperArmletL","DisplayCategory","ClothArm");
TweakItem("Base.StormTrooperArmletR","DisplayCategory","ClothArm");
TweakItem("Base.StormTrooperArmor","DisplayCategory","ClothBody");
TweakItem("Base.StormTrooperBelt","DisplayCategory","ClothAcc");
TweakItem("Base.StormTrooperHelmet","DisplayCategory","ClothHead");
TweakItem("Base.StormTrooperShoulders","DisplayCategory","ClothArm");
TweakItem("Base.Shoes_StormTrooperBoots","DisplayCategory","ClothFeet");
TweakItem("Base.StormTrooperLegs","DisplayCategory","ClothLeg");
end
