require("ItemTweaker_Copy_CC");

--KCMCROSSBOW
--https://steamcommunity.com/sharedfiles/filedetails/?id=2205190407
--https://steamcommunity.com/sharedfiles/filedetails/?id=2572385719
if getActivatedMods():contains("TKCM") or getActivatedMods():contains("Remastered Kitsune's Crossbow Mod") then
TweakItem("KCMweapons.KCM_Flax","DisplayCategory","Craft");
TweakItem("KCMweapons.CrossbowBoltShaft","DisplayCategory","Craft");
TweakItem("KCMweapons.CrossbowBoltParts","DisplayCategory","Craft");
TweakItem("KCMweapons.CrossbowBolt","DisplayCategory","Ammo");
TweakItem("KCMweapons.CrossbowBoltBox","DisplayCategory","Ammo");
TweakItem("KCMweapons.CrossbowBoltLarge","DisplayCategory","Ammo");
TweakItem("KCMweapons.CrossbowBoltLargeBox","DisplayCategory","Ammo");
TweakItem("KCMweapons.WoodenBolt","DisplayCategory","Ammo");
TweakItem("KCMweapons.WoodenBoltBox","DisplayCategory","Ammo");
TweakItem("Base.KCM_IronSight","DisplayCategory","WepPart");
TweakItem("Base.KCM_x2Scope","DisplayCategory","WepPart");
TweakItem("Base.KCM_x4Scope","DisplayCategory","WepPart");
TweakItem("Base.KCM_x8Scope","DisplayCategory","WepPart");
TweakItem("Base.KCM_Sling","DisplayCategory","WepPart");
TweakItem("Base.KCM_FiberglassStock","DisplayCategory","WepPart");
TweakItem("Base.KCM_RedDot","DisplayCategory","WepPart");
TweakItem("KCMweapons.HandCrossbow","DisplayCategory","WepBow");
TweakItem("KCMweapons.LargeCrossbow","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Compound","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Compound02","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Handmade","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Handmade02","DisplayCategory","WepBow");
TweakItem("KCMweapons.TheUltimateHuntingGuide","DisplayCategory","LitR");
TweakItem("KCMweapons.WeaponHandlersReloaded","DisplayCategory","LitR");
TweakItem("KCMweapons.DoomsdayPreppers1","DisplayCategory","LitR");
TweakItem("KCMweapons.DoomsdayPreppers2","DisplayCategory","LitR");
TweakItem("KCMweapons.DoomsdayPreppers3","DisplayCategory","LitR");
TweakItem("KCMweapons.ShortBrokenBolt","DisplayCategory","Craft");
TweakItem("KCMweapons.LongBrokenBolt","DisplayCategory","Craft");
TweakItem("KCMweapons.WoodenBrokenBolt","DisplayCategory","Craft");
TweakItem("KCMweapons.ShortShaft","DisplayCategory","Craft");
TweakItem("KCMweapons.LongShaft","DisplayCategory","Craft");
TweakItem("KCMweapons.CrossbowBoltHead","DisplayCategory","Craft");
TweakItem("KCMweapons.CrossbowBoltFletching","DisplayCategory","Craft");
end
