require("ItemTweaker_Copy_CC");

--59Meteor
TweakItem("Base.ECTO1tire2_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1tire1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1Trunk2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1Extra2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1Roofrack1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1Equipment1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarFrontDoor2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarRearDoor2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarFrontDoorArmor1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarRearDoorArmor1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1WindshieldArmor1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1WindshieldRearArmor1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1Bullbar1_Item","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1EngineDoor2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1TrunkDoor2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarSeatfl2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarSeatfr2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarSeatrl2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1CarSeatrr2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1DefaultInterior2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1Windshield2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1RearWindshield2","DisplayCategory","Mechanics");
TweakItem("Base.ECTO1SideWindow2","DisplayCategory","Mechanics");
--67Commando
TweakItem("Base.V100Tire2","DisplayCategory","Mechanics");
TweakItem("Base.FrontLeftV100Door2","DisplayCategory","Mechanics");
TweakItem("Base.FrontRightV100Door2","DisplayCategory","Mechanics");
TweakItem("Base.RearV100Door2","DisplayCategory","Mechanics");
TweakItem("Base.V100Window2","DisplayCategory","Mechanics");
--85Merc
TweakItem("Base.mercroofrack1","DisplayCategory","Mechanics");
TweakItem("Base.mercroofrack2","DisplayCategory","Mechanics");
TweakItem("Base.mercroofrack3","DisplayCategory","Mechanics");
--87Cruiser
TweakItem("Base.cruiserRoofrack1","DisplayCategory","Mechanics");
TweakItem("Base.cruiserRoofrack2","DisplayCategory","Mechanics");
TweakItem("Base.cruiserRoofrack3","DisplayCategory","Mechanics");
--89Defender90
TweakItem("Base.def90SpareCompartment1","DisplayCategory","Mechanics");
TweakItem("Base.def90SpareCompartment2","DisplayCategory","Mechanics");
TweakItem("Base.def90SpareCompartment3","DisplayCategory","Mechanics");
--89Defender110
TweakItem("Base.def110SpareCompartment1","DisplayCategory","Mechanics");
TweakItem("Base.def110SpareCompartment2","DisplayCategory","Mechanics");
TweakItem("Base.def110SpareCompartment3","DisplayCategory","Mechanics");
--92AMGeneralM998
TweakItem("Base.V100Tire2","DisplayCategory","Mechanics");
TweakItem("Base.V101Tire2","DisplayCategory","Mechanics");
TweakItem("Base.M998Trunk2","DisplayCategory","Mechanics");
TweakItem("Base.M998Extra2","DisplayCategory","Mechanics");
TweakItem("Base.M998Roofrack1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998TrunkBarrier1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998TrunkBarrier2_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998SpareMount_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998SpareTireMount_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998CarFrontDoor2","DisplayCategory","Mechanics");
TweakItem("Base.M998CarRearDoor2","DisplayCategory","Mechanics");
TweakItem("Base.M998CarFrontDoorArmor1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998CarRearDoorArmor1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998WindshieldArmor1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998WindshieldArmor2_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998EngineDoor2","DisplayCategory","Mechanics");
TweakItem("Base.M998TrunkDoor2","DisplayCategory","Mechanics");
TweakItem("Base.M998BackCover1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998CarSeat2","DisplayCategory","Mechanics");
TweakItem("Base.M998Muffler1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998Muffler2_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998Bullbar1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998Bullbar2_Item","DisplayCategory","Mechanics");
TweakItem("Base.M998DefaultInterior2","DisplayCategory","Mechanics");
TweakItem("Base.M998Windshield2","DisplayCategory","Mechanics");
TweakItem("Base.M998SideWindow2","DisplayCategory","Mechanics");
TweakItem("Base.M998Mudflaps1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M101A3Trunk2","DisplayCategory","Mechanics");
TweakItem("Base.M101A3Extra2","DisplayCategory","Mechanics");
TweakItem("Base.M101A3TrunkDoor2","DisplayCategory","Mechanics");
TweakItem("Base.M101A3TrunkDoorTwo2","DisplayCategory","Mechanics");
TweakItem("Base.M101A3Cover1_Item","DisplayCategory","Mechanics");
TweakItem("Base.M101A3Tarp1_Item","DisplayCategory","Mechanics");
TweakItem("Base.leafSuspension2","DisplayCategory","Mechanics");
--ISOContainers
TweakItem("Base.IsoContainerTrunkDoor2","DisplayCategory","Mechanics");
TweakItem("Base.IsoContainerTankerTrunkDoor2","DisplayCategory","Mechanics");
--Oshkosh82M911
TweakItem("OshkoshShirts.TShirt_OshkoshGray","DisplayCategory","Cloth");
TweakItem("OshkoshShirts.TShirt_OshkoshBlack","DisplayCategory","Cloth");
TweakItem("OshkoshShirts.TShirt_bknht","DisplayCategory","Cloth");
TweakItem("OshkoshShirts.Hoodie_OshkoshBlack","DisplayCategory","Cloth");
TweakItem("OshkoshShirts.HoodieDOWN_OshkoshBlack","DisplayCategory","Cloth");
TweakItem("OshkoshShirts.Hoodie_OshkoshGray","DisplayCategory","Cloth");
TweakItem("OshkoshShirts.HoodieDOWN_OshkoshGray","DisplayCategory","Cloth");
TweakItem("Base.V100Tire2","DisplayCategory","Mechanics");
TweakItem("Base.V100Tires2","DisplayCategory","Mechanics");
TweakItem("Base.V100Axle2","DisplayCategory","Mechanics");
TweakItem("Base.V100AxleSmall2","DisplayCategory","Mechanics");
TweakItem("Base.M911Trunk2","DisplayCategory","Mechanics");
TweakItem("Base.M911Toolbox2","DisplayCategory","Mechanics");
TweakItem("Base.M911SpareTire2","DisplayCategory","Mechanics");
--Oshkosh86P19A
TweakItem("Base.V100Tire2","DisplayCategory","Mechanics");
TweakItem("Base.P19ARoofHatch2","DisplayCategory","Mechanics");
TweakItem("Base.P19ABigTrunk2","DisplayCategory","Mechanics");
TweakItem("Base.P19ASmallTrunk2","DisplayCategory","Mechanics");