require("ItemTweaker_Copy_CC");
--Not Required: '08 Mercury Sable, '88 Volkswagen Golf Mk2, '88 Volkswagen Jetta Mk2, '90 Lada Niva

--49powerWagon
--https://steamcommunity.com/sharedfiles/filedetails/?id=2900580391
if getActivatedMods():contains("49powerWagon") then
TweakItem("Base.49powerWagonTire","DisplayCategory","Mech");
TweakItem("Base.49powerWagonApocalypseTire","DisplayCategory","Mech");
TweakItem("Base.PWRTrunk2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonSideskirts0","DisplayCategory","Mech");
TweakItem("Base.49powerWagonSideskirts1","DisplayCategory","Mech");
TweakItem("Base.49powerWagonFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonRearDoor2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonFrontDoorArmor","DisplayCategory","Mech");
TweakItem("Base.49powerWagonRearDoorArmor","DisplayCategory","Mech");
TweakItem("Base.49powerWagonWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.49powerWagonWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.49powerWagonEngineDoor2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonSeat2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonTruckBedSeat2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonBumper0","DisplayCategory","Mech");
TweakItem("Base.49powerWagonBullbar1","DisplayCategory","Mech");
TweakItem("Base.49powerWagonBullbar2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonWindshield2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonSideWindow2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonWindshieldRear2","DisplayCategory","Mech");
TweakItem("Base.49powerWagonFrontFender","DisplayCategory","Mech");
TweakItem("Base.49powerWagonRearFender","DisplayCategory","Mech");
TweakItem("Base.49powerWagonFrontFenderMakeshift","DisplayCategory","Mech");
TweakItem("Base.49powerWagonRearFenderMakeshift","DisplayCategory","Mech");
end

--59Meteor
--https://steamcommunity.com/sharedfiles/filedetails/?id=2772575623
if getActivatedMods():contains("59meteor") or getActivatedMods():contains("ECTO1") then
TweakItem("Base.ECTO1tire2_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1tire1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1Trunk2","DisplayCategory","Mech");
TweakItem("Base.ECTO1Extra2","DisplayCategory","Mech");
TweakItem("Base.ECTO1Roofrack1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1Equipment1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarRearDoor2","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarFrontDoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarRearDoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1WindshieldArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1WindshieldRearArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1Bullbar1_Item","DisplayCategory","Mech");
TweakItem("Base.ECTO1EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.ECTO1TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarSeatfl2","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarSeatfr2","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarSeatrl2","DisplayCategory","Mech");
TweakItem("Base.ECTO1CarSeatrr2","DisplayCategory","Mech");
TweakItem("Base.ECTO1DefaultInterior2","DisplayCategory","Mech");
TweakItem("Base.ECTO1Windshield2","DisplayCategory","Mech");
TweakItem("Base.ECTO1RearWindshield2","DisplayCategory","Mech");
TweakItem("Base.ECTO1SideWindow2","DisplayCategory","Mech");
end

--67Commando
--https://steamcommunity.com/sharedfiles/filedetails/?id=2478247379
if getActivatedMods():contains("67commando") then
TweakItem("Base.V100Tire2","DisplayCategory","Mech");
TweakItem("Base.FrontLeftV100Door2","DisplayCategory","Mech");
TweakItem("Base.FrontRightV100Door2","DisplayCategory","Mech");
TweakItem("Base.RearV100Door2","DisplayCategory","Mech");
TweakItem("Base.V100Window2","DisplayCategory","Mech");
TweakItem("Base.V100EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.V100ToolboxLid2","DisplayCategory","Mech");
TweakItem("Base.V100Toolbox2","DisplayCategory","Mech");
TweakItem("USMIL.Seat0","DisplayCategory","Mech");
end

--69mini
--https://steamcommunity.com/sharedfiles/filedetails/?id=2937786633
if getActivatedMods():contains("69mini") then
TweakItem("Base.49powerWagonTire","DisplayCategory","Mech");
TweakItem("Base.69miniTire1","DisplayCategory","Mech");
TweakItem("Base.69miniTirePS1","DisplayCategory","Mech");
TweakItem("Base.69miniTrunkSmall1","DisplayCategory","Mech");
TweakItem("Base.69miniTrunkLarge1","DisplayCategory","Mech");
TweakItem("Base.69miniRoofrack1","DisplayCategory","Mech");
TweakItem("Base.69miniFrontDoor1","DisplayCategory","Mech");
TweakItem("Base.69miniFrontDoorArmor","DisplayCategory","Mech");
TweakItem("Base.69miniRearWindowArmor","DisplayCategory","Mech");
TweakItem("Base.69miniWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.69miniWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.69miniEngineDoor1","DisplayCategory","Mech");
TweakItem("Base.69miniEngineDoorBelts1","DisplayCategory","Mech");
TweakItem("Base.69miniEngineDoorPitbull1","DisplayCategory","Mech");
TweakItem("Base.69miniTrunkDoor1","DisplayCategory","Mech");
TweakItem("Base.69miniSeatFront1","DisplayCategory","Mech");
TweakItem("Base.69miniSeatRear1","DisplayCategory","Mech");
TweakItem("Base.69miniMrBChair1","DisplayCategory","Mech");
TweakItem("Base.69miniBumperFront0","DisplayCategory","Mech");
TweakItem("Base.69miniBumperFront1","DisplayCategory","Mech");
TweakItem("Base.69miniBumperFront2","DisplayCategory","Mech");
TweakItem("Base.69miniBumperRear0","DisplayCategory","Mech");
TweakItem("Base.69miniBumperRear1","DisplayCategory","Mech");
TweakItem("Base.69miniWindshield1","DisplayCategory","Mech");
TweakItem("Base.69miniSideWindowFront1","DisplayCategory","Mech");
TweakItem("Base.69miniSideWindowRear1","DisplayCategory","Mech");
TweakItem("Base.69miniRearWindshield1","DisplayCategory","Mech");
TweakItem("Base.69miniCrumpet","DisplayCategory","FoodP");
TweakItem("Base.69miniGoldBullions","DisplayCategory","Junk");
TweakItem("Base.69miniMeatballBulldog","DisplayCategory","Collect");
TweakItem("Base.69miniRupertBear","DisplayCategory","Collect");
TweakItem("Base.69miniTeddy","DisplayCategory","Collect");
TweakItem("Base.69miniTeaCrate","DisplayCategory","Junk");
TweakItem("Base.69miniCrateOfTea","DisplayCategory","FoodB");
end

--70dodge
--https://steamcommunity.com/sharedfiles/filedetails/?id=2873290424
if getActivatedMods():contains("70dodge") then
TweakItem("Base.DodgeRTtire3","DisplayCategory","Mech");
TweakItem("Base.CUDAtire3","DisplayCategory","Mech");
TweakItem("Base.DG70Trunk3","DisplayCategory","Mech");
TweakItem("Base.DodgeFrontSeat3","DisplayCategory","Mech");
TweakItem("Base.DodgeRearSeat3","DisplayCategory","Mech");
TweakItem("Base.DG70RTEngineDoor","DisplayCategory","Mech");
TweakItem("Base.DG70PDEngineDoor","DisplayCategory","Mech");
TweakItem("Base.DG70TAEngineDoor0","DisplayCategory","Mech");
TweakItem("Base.DG70TAEngineDoor1","DisplayCategory","Mech");
TweakItem("Base.DG70TrunkDoor3","DisplayCategory","Mech");
TweakItem("Base.DG70Door3","DisplayCategory","Mech");
TweakItem("Base.DG70FrontSideWindow3","DisplayCategory","Mech");
TweakItem("Base.DG70RearSideWindow3","DisplayCategory","Mech");
TweakItem("Base.DG70Windshield3","DisplayCategory","Mech");
TweakItem("Base.DG70WindshieldRear3","DisplayCategory","Mech");
TweakItem("Base.DG70FrontBumper0","DisplayCategory","Mech");
TweakItem("Base.DG70RearBumper0","DisplayCategory","Mech");
TweakItem("Base.DG70FrontBumperA","DisplayCategory","Mech");
TweakItem("Base.DG70FrontBumperB","DisplayCategory","Mech");
TweakItem("Base.DG70FrontBumperC","DisplayCategory","Mech");
TweakItem("Base.DG70RearBumperA","DisplayCategory","Mech");
TweakItem("Base.DG70RearBumperB","DisplayCategory","Mech");
TweakItem("Base.DG70RearBumperC","DisplayCategory","Mech");
TweakItem("Base.DG70WindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.DG70WindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.DG70DoorArmor","DisplayCategory","Mech");
TweakItem("Base.DG70Spoiler0","DisplayCategory","Mech");
TweakItem("Base.DG70Spoiler1","DisplayCategory","Mech");
TweakItem("Base.DG70RTRoof0","DisplayCategory","Mech");
end

--70barracuda
--https://steamcommunity.com/sharedfiles/filedetails/?id=2913633066
if getActivatedMods():contains("70barracuda") then
TweakItem("Base.CUDAtire3","DisplayCategory","Mech");
TweakItem("Base.DodgeRTtire3","DisplayCategory","Mech");
TweakItem("Base.CUDATrunk3","DisplayCategory","Mech");
TweakItem("Base.CUDAFrontSeat3","DisplayCategory","Mech");
TweakItem("Base.CUDARearSeat3","DisplayCategory","Mech");
TweakItem("Base.CUDAEngineDoorStock","DisplayCategory","Mech");
TweakItem("Base.CUDAEngineDoor","DisplayCategory","Mech");
TweakItem("Base.CUDAEngineDoorAAR","DisplayCategory","Mech");
TweakItem("Base.CUDATrunkDoor3","DisplayCategory","Mech");
TweakItem("Base.CUDADoor3","DisplayCategory","Mech");
TweakItem("Base.CUDAFrontSideWindow3","DisplayCategory","Mech");
TweakItem("Base.CUDARearSideWindow3","DisplayCategory","Mech");
TweakItem("Base.CUDAWindshield3","DisplayCategory","Mech");
TweakItem("Base.CUDAWindshieldRear3","DisplayCategory","Mech");
TweakItem("Base.CUDAFrontBumper0","DisplayCategory","Mech");
TweakItem("Base.CUDAFrontBumper1","DisplayCategory","Mech");
TweakItem("Base.CUDAFrontBumper2","DisplayCategory","Mech");
TweakItem("Base.CUDARearBumper0","DisplayCategory","Mech");
TweakItem("Base.CUDAFrontBumperA","DisplayCategory","Mech");
TweakItem("Base.CUDARearBumperA","DisplayCategory","Mech");
TweakItem("Base.CUDAWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.CUDAWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.CUDADoorArmor","DisplayCategory","Mech");
TweakItem("Base.CUDASpoiler0","DisplayCategory","Mech");
TweakItem("Base.CUDASpoiler1","DisplayCategory","Mech");
end

--74amgeneralM151A2
--https://steamcommunity.com/sharedfiles/filedetails/?id=2785549133
if getActivatedMods():contains("74amgeneralM151A2") then
TweakItem("Base.V100Tire2","DisplayCategory","Mech");
TweakItem("Base.V102Tire2","DisplayCategory","Mech");
TweakItem("Base.M151A2Trunk2","DisplayCategory","Mech");
TweakItem("Base.M151A2Extra2","DisplayCategory","Mech");
TweakItem("Base.M151A2EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.M151A2Tarp1_Item","DisplayCategory","Mech");
TweakItem("Base.M151A2CarSeatFront2","DisplayCategory","Mech");
TweakItem("Base.M151A2CarSeatRear2","DisplayCategory","Mech");
TweakItem("Base.M151A2Bumper1_Item","DisplayCategory","Mech");
TweakItem("Base.M998Bullbar1_Item","DisplayCategory","Mech");
TweakItem("Base.M151A2DefaultInterior2","DisplayCategory","Mech");
TweakItem("Base.M151A2Windshield2","DisplayCategory","Mech");
TweakItem("Base.M151A2SideWindow2","DisplayCategory","Mech");
TweakItem("Base.M151A2LeftDoor2","DisplayCategory","Mech");
TweakItem("Base.M151A2RightDoor2","DisplayCategory","Mech");
TweakItem("Base.M151A2WindshieldArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M151A2CabArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M151A2BarrierLeft1_Item","DisplayCategory","Mech");
TweakItem("Base.M151A2BarrierRight1_Item","DisplayCategory","Mech");
end

--78amgeneralM35A2
--https://steamcommunity.com/sharedfiles/filedetails/?id=2799152995
if getActivatedMods():contains("78amgeneralM35A2") then
TweakItem("Base.V100Tire2","DisplayCategory","Mech");
TweakItem("Base.V103Tire2","DisplayCategory","Mech");
TweakItem("Base.V103Axle2","DisplayCategory","Mech");
TweakItem("Base.M35A2Trunk2","DisplayCategory","Mech");
TweakItem("Base.M49A2CTrunk2","DisplayCategory","Mech");
TweakItem("Base.M35A2Muffler1_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.M35A2Tarp1_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2Tarp2_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2Tarp3_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2tailgate2","DisplayCategory","Mech");
TweakItem("Base.M35A2CarSeat2","DisplayCategory","Mech");
TweakItem("Base.M35A2Bumper1_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2Grille1_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2HardCover1_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2SoftCover2_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2Windshield2","DisplayCategory","Mech");
TweakItem("Base.M35A2SideWindow2","DisplayCategory","Mech");
TweakItem("Base.M35A2Door2","DisplayCategory","Mech");
TweakItem("Base.M35A2WindshieldArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2DoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M35A2Mudflaps1_Item","DisplayCategory","Mech");
TweakItem("Base.M49PumpDoor2","DisplayCategory","Mech");
TweakItem("Base.500_Water_Tank2","DisplayCategory","Mech");
end

--80kz1000
--https://steamcommunity.com/sharedfiles/filedetails/?id=2818847163
if getActivatedMods():contains("80kz1000") then
TweakItem("Base.KZ1Kstorage3","DisplayCategory","Mech");
TweakItem("Base.KZ1Ksidestorage3","DisplayCategory","Mech");
TweakItem("Base.KZ1Kextra3","DisplayCategory","Mech");
TweakItem("Base.KZ1KstorageLid","DisplayCategory","Mech");
TweakItem("Base.KZ1KsidestorageLid","DisplayCategory","Mech");
TweakItem("Base.KZ1Kmuffler","DisplayCategory","Mech");
TweakItem("Base.KZ1KoldTire","DisplayCategory","Mech");
TweakItem("Base.KZ1KnormalTire","DisplayCategory","Mech");
TweakItem("Base.KZ1KmodernTire","DisplayCategory","Mech");
TweakItem("Base.KZ1KgasTank","DisplayCategory","Mech");
TweakItem("Base.KZ1Kseat","DisplayCategory","Mech");
TweakItem("Base.KZ1Kwindshield3","DisplayCategory","Mech");
TweakItem("Base.Hat_CHiPsHelmet","DisplayCategory","ClothHead");
end

--82jeepJ10
--https://steamcommunity.com/sharedfiles/filedetails/?id=2886832257
if getActivatedMods():contains("82jeepJ10") then
TweakItem("Base.80sOffroadTireA","DisplayCategory","Mech");
TweakItem("Base.80sPickupRoofrackA","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindowFrontArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindowRearArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupBullbarFront","DisplayCategory","Mech");
TweakItem("Base.80sPickupBullbarRear","DisplayCategory","Mech");
TweakItem("Base.80sPickupSeatFront2","DisplayCategory","Mech");
TweakItem("Base.80sPickupSeatRear2","DisplayCategory","Mech");
TweakItem("Base.80sPickupRollbarA","DisplayCategory","Mech");
TweakItem("Base.80sPickupRollbarB","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10Trunk2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10Trunkt2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10CarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10TrunkDoorTop2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10BumperFront","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10BullbarFront","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10BumperRear","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10Windshield2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10WindowSide2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10WindshieldRear2","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10BedCover","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10Dorothy","DisplayCategory","Mech");
TweakItem("Base.82JeepJ10DorothyAnemometer","DisplayCategory","Mech");
end

--82oshkoshM911
--https://steamcommunity.com/sharedfiles/filedetails/?id=2618213077
if getActivatedMods():contains("82oshkoshM911") then
TweakItem("OshkoshShirts.TShirt_OshkoshGray","DisplayCategory","ClothBody");
TweakItem("OshkoshShirts.TShirt_OshkoshGray","DisplayCategory","ClothBody");
TweakItem("OshkoshShirts.TShirt_OshkoshBlack","DisplayCategory","ClothBody");
TweakItem("OshkoshShirts.TShirt_bknht","DisplayCategory","ClothBody");
TweakItem("OshkoshShirts.Hoodie_OshkoshBlack","DisplayCategory","ClothBody");
TweakItem("OshkoshShirts.HoodieDOWN_OshkoshBlack","DisplayCategory","ClothBody");
TweakItem("OshkoshShirts.Hoodie_OshkoshGray","DisplayCategory","ClothBody");
TweakItem("OshkoshShirts.HoodieDOWN_OshkoshGray","DisplayCategory","ClothBody");
TweakItem("Base.M911Trunk2","DisplayCategory","Mech");
TweakItem("Base.M967SmallTrunk2","DisplayCategory","Mech");
TweakItem("Base.M911Toolbox2","DisplayCategory","Mech");
TweakItem("Base.M911EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.M911TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.M127TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.M128TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.M129TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.M967TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.IsoContainerTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.M911CarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.M911Windshield2","DisplayCategory","Mech");
TweakItem("Base.M911SideWindow2","DisplayCategory","Mech");
TweakItem("Base.M911WindshieldRear2","DisplayCategory","Mech");
TweakItem("Base.M911CarFrontDoorArmor","DisplayCategory","Mech");
TweakItem("Base.M911WindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.M911WindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.M911Bullbar0","DisplayCategory","Mech");
TweakItem("Base.M911Bullbar1","DisplayCategory","Mech");
TweakItem("Base.M911Muffler","DisplayCategory","Mech");
TweakItem("Base.M911Mudflaps","DisplayCategory","Mech");
TweakItem("Base.V100Tire2","DisplayCategory","Mech");
TweakItem("Base.V100Tires2","DisplayCategory","Mech");
TweakItem("Base.V100Axle2","DisplayCategory","Mech");
TweakItem("Base.V100AxleSmall2","DisplayCategory","Mech");
TweakItem("USMIL.Seat0","DisplayCategory","Mech");
end

--83AMGeneralM923
--https://steamcommunity.com/sharedfiles/filedetails/?id=2811383142
if getActivatedMods():contains("83amgeneralM923") then
TweakItem("Base.V100Tire2","DisplayCategory","Mech");
TweakItem("Base.M923Axle2","DisplayCategory","Mech");
TweakItem("Base.M923Trunk2","DisplayCategory","Mech");
TweakItem("Base.M923Flatbed2","DisplayCategory","Mech");
TweakItem("Base.M923Extra2","DisplayCategory","Mech");
TweakItem("Base.M923Muffler1_Item","DisplayCategory","Mech");
TweakItem("Base.M923EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.M923FlatbedStakes1_Item","DisplayCategory","Mech");
TweakItem("Base.M923Tailgate2","DisplayCategory","Mech");
TweakItem("Base.M923Trunkdoor2","DisplayCategory","Mech");
TweakItem("Base.M923FrontSeat2","DisplayCategory","Mech");
TweakItem("Base.M923RearSeat2","DisplayCategory","Mech");
TweakItem("Base.M923Bumper1_Item","DisplayCategory","Mech");
TweakItem("Base.M923Bumper2_Item","DisplayCategory","Mech");
TweakItem("Base.M923HardCover1_Item","DisplayCategory","Mech");
TweakItem("Base.M923SoftCover2_Item","DisplayCategory","Mech");
TweakItem("Base.M923Windshield2","DisplayCategory","Mech");
TweakItem("Base.M923SideWindow2","DisplayCategory","Mech");
TweakItem("Base.M923Gunport2","DisplayCategory","Mech");
TweakItem("Base.M923Door2","DisplayCategory","Mech");
TweakItem("Base.M923WindshieldArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M923DoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M923GuntruckArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M923Mudflaps1_Item","DisplayCategory","Mech");
TweakItem("Base.M923SpareMount1_Item","DisplayCategory","Mech");
end

--84Merc
--https://steamcommunity.com/sharedfiles/filedetails/?id=2805630347
if getActivatedMods():contains("84merc") then
TweakItem("Base.W460NormalTire2","DisplayCategory","Mech");
TweakItem("Base.W460WideTire2","DisplayCategory","Mech");
TweakItem("Base.W460ModernTire2","DisplayCategory","Mech");
TweakItem("Base.W460Trunk2","DisplayCategory","Mech");
TweakItem("Base.W4602Trunk2","DisplayCategory","Mech");
TweakItem("Base.W4604Trunk2","DisplayCategory","Mech");
TweakItem("Base.W460Extra2","DisplayCategory","Mech");
TweakItem("Base.W460Roofrack1_Item","DisplayCategory","Mech");
TweakItem("Base.W460Bodykit1_Item","DisplayCategory","Mech");
TweakItem("Base.W460CarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.W460CarRearDoor2","DisplayCategory","Mech");
TweakItem("Base.W460CarFrontDoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.W460CarRearDoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.W460WindshieldArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.W460WindshieldRearArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.W460WindowArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.W460EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.W460TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.W460CarSeatFront2","DisplayCategory","Mech");
TweakItem("Base.W460CarSeatRear2","DisplayCategory","Mech");
TweakItem("Base.W460Bumper1_Item","DisplayCategory","Mech");
TweakItem("Base.W460Bullbar2_Item","DisplayCategory","Mech");
TweakItem("Base.W460Bullbar3_Item","DisplayCategory","Mech");
TweakItem("Base.W460BumperRear1_Item","DisplayCategory","Mech");
TweakItem("Base.W460Windshield2","DisplayCategory","Mech");
TweakItem("Base.W460SideWindow2","DisplayCategory","Mech");
TweakItem("Base.W460RearWindshield2","DisplayCategory","Mech");
TweakItem("Base.W460Mudflaps1_Item","DisplayCategory","Mech");
end

--85Merc
--https://steamcommunity.com/sharedfiles/filedetails/?id=2469388752
if getActivatedMods():contains("85merc") then
TweakItem("Base.mercroofrack1","DisplayCategory","Mech");
TweakItem("Base.mercroofrack2","DisplayCategory","Mech");
TweakItem("Base.mercroofrack3","DisplayCategory","Mech");
end

--86fordE150
--https://steamcommunity.com/sharedfiles/filedetails/?id=2870394916
if getActivatedMods():contains("86fordE150") then
TweakItem("Base.Hat_chains_mask","DisplayCategory","ClothBody");
TweakItem("Base.Hat_chains_mask_blank","DisplayCategory","ClothBody");
TweakItem("Base.Hat_dallas_mask","DisplayCategory","ClothBody");
TweakItem("Base.Hat_dallas_mask_blank","DisplayCategory","ClothBody");
TweakItem("Base.Hat_hoxton_mask","DisplayCategory","ClothBody");
TweakItem("Base.Hat_hoxton_mask_blank","DisplayCategory","ClothBody");
TweakItem("Base.Hat_wolf_mask","DisplayCategory","ClothBody");
TweakItem("Base.Hat_wolf_mask_blank","DisplayCategory","ClothBody");
TweakItem("Base.PaydayGoldBars","DisplayCategory","Misc");
TweakItem("Base.PaydayAmmoBag","DisplayCategory","Cont");
TweakItem("Base.PaydayBodyBagCase","DisplayCategory","Cont");
TweakItem("Base.PaydayMedicBag","DisplayCategory","Cont");
TweakItem("Base.PaydayCoke","DisplayCategory","Drugs");
TweakItem("Base.PaydayFirstAidKit","DisplayCategory","Med");
TweakItem("Base.PaydayToothbrush","DisplayCategory","Junk");
TweakItem("Base.PaydayLootBag","DisplayCategory","Cont");
TweakItem("Base.PaydayLootBagOrange","DisplayCategory","Cont");
TweakItem("Base.PaydayLootBagYellow","DisplayCategory","Cont");
TweakItem("Base.PaydayLootBagGreen","DisplayCategory","Cont");
TweakItem("Base.PaydayMerchBag","DisplayCategory","Cont");
TweakItem("Base.PaydayMeth","DisplayCategory","Drugs");
TweakItem("Base.PaydayMoneyPile","DisplayCategory","Misc");
TweakItem("Base.E150Tire2","DisplayCategory","Mech");
TweakItem("Base.E150dndTrunk2","DisplayCategory","Mech");
TweakItem("Base.E150pdTrunk2","DisplayCategory","Mech");
TweakItem("Base.E150slideTrunk2","DisplayCategory","Mech");
TweakItem("Base.E150longTrunk2","DisplayCategory","Mech");
TweakItem("Base.E150CarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.E150CarSlideDoor2","DisplayCategory","Mech");
TweakItem("Base.E150EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.E150TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.E150CarSeat2","DisplayCategory","Mech");
TweakItem("Base.E150FrontBumper2","DisplayCategory","Mech");
TweakItem("Base.E150RearBumper2","DisplayCategory","Mech");
TweakItem("Base.E150Windshield2","DisplayCategory","Mech");
TweakItem("Base.E150SideWindow2","DisplayCategory","Mech");
TweakItem("Base.E150RearWindshield2","DisplayCategory","Mech");
TweakItem("Base.E150WindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.E150WindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.E150DoorArmor","DisplayCategory","Mech");
TweakItem("Base.E150HoodFur","DisplayCategory","Mech");
TweakItem("Base.E150TrunkDoorFur","DisplayCategory","Mech");
TweakItem("Base.E150DoorFur","DisplayCategory","Mech");
TweakItem("Base.E150ChassisFur","DisplayCategory","Mech");
TweakItem("Base.E150LegFur","DisplayCategory","Mech");
TweakItem("Base.E150Divider","DisplayCategory","Mech");
TweakItem("Base.E150MysteryMachineRoofrack2","DisplayCategory","Mech");
TweakItem("Base.E150MysteryMachineSurfboards2","DisplayCategory","Mech");
end

--86oshkoshP19A
--https://steamcommunity.com/sharedfiles/filedetails/?id=2566953935
if getActivatedMods():contains("86oshkoshP19A") then
TweakItem("Base.V100Tire2","DisplayCategory","Mech");
TweakItem("Base.P19ACarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.P19ARoofHatch2","DisplayCategory","Mech");
TweakItem("Base.P19ABigTrunk2","DisplayCategory","Mech");
TweakItem("Base.P19ASmallTrunk2","DisplayCategory","Mech");
TweakItem("Base.P19ARoofrack1_Item","DisplayCategory","Mech");
TweakItem("Base.P19ACarSeat2","DisplayCategory","Mech");
TweakItem("Base.P19AEngineDoor2","DisplayCategory","Mech");
TweakItem("Base.P19ATrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.P19AWindshield2","DisplayCategory","Mech");
TweakItem("Base.P19ASideWindow2","DisplayCategory","Mech");
TweakItem("Base.P19ACarFrontDoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.P19AWindshieldArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.P19AFenderLeft1_Item","DisplayCategory","Mech");
TweakItem("Base.P19AFenderLeft2_Item","DisplayCategory","Mech");
TweakItem("Base.P19AFenderRight1_Item","DisplayCategory","Mech");
TweakItem("Base.P19AFenderRight2_Item","DisplayCategory","Mech");
TweakItem("Base.P19AFenderRight3_Item","DisplayCategory","Mech");
TweakItem("Base.P19ASpareMount1_Item","DisplayCategory","Mech");
TweakItem("Base.P19ASpareMount2_Item","DisplayCategory","Mech");
TweakItem("USMIL.Seat0","DisplayCategory","Mech");
end

--87Cruiser
--https://steamcommunity.com/sharedfiles/filedetails/?id=2489148104
if getActivatedMods():contains("87cruiser") then
TweakItem("Base.cruiserRoofrack1","DisplayCategory","Mech");
TweakItem("Base.cruiserRoofrack2","DisplayCategory","Mech");
TweakItem("Base.cruiserRoofrack3","DisplayCategory","Mech");
end

--88chevyS10
--https://steamcommunity.com/sharedfiles/filedetails/?id=2886832936
if getActivatedMods():contains("88chevyS10") then
TweakItem("Base.80sOffroadTireA","DisplayCategory","Mech");
TweakItem("Base.80sPickupRoofrackA","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindowFrontArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindowRearArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupBullbarFront","DisplayCategory","Mech");
TweakItem("Base.80sPickupBullbarRear","DisplayCategory","Mech");
TweakItem("Base.80sPickupSeatFront2","DisplayCategory","Mech");
TweakItem("Base.80sPickupSeatRear2","DisplayCategory","Mech");
TweakItem("Base.80sPickupRollbarA","DisplayCategory","Mech");
TweakItem("Base.80sPickupRollbarB","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10Trunk2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10CarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10TrunkDoorTop2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10BumperFront","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10BullbarFront","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10BumperRear","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10Windshield2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10WindowSide2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10WindshieldRear2","DisplayCategory","Mech");
TweakItem("Base.88ChevyS10BedCover","DisplayCategory","Mech");
end

--89fordBronco
--https://steamcommunity.com/sharedfiles/filedetails/?id=2886833398
if getActivatedMods():contains("89fordBronco") then
TweakItem("Base.80sOffroadTireA","DisplayCategory","Mech");
TweakItem("Base.80sPickupRoofrackA","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindowFrontArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupWindowRearArmor","DisplayCategory","Mech");
TweakItem("Base.80sPickupBullbarFront","DisplayCategory","Mech");
TweakItem("Base.80sPickupBullbarRear","DisplayCategory","Mech");
TweakItem("Base.80sPickupSeatFront2","DisplayCategory","Mech");
TweakItem("Base.80sPickupSeatRear2","DisplayCategory","Mech");
TweakItem("Base.80sPickupRollbarA","DisplayCategory","Mech");
TweakItem("Base.80sPickupRollbarB","DisplayCategory","Mech");
TweakItem("Base.89BroncoTrunk2","DisplayCategory","Mech");
TweakItem("Base.89BroncoCarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.89BroncoEngineDoor2","DisplayCategory","Mech");
TweakItem("Base.89BroncoTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.89BroncoBumperFront","DisplayCategory","Mech");
TweakItem("Base.89BroncoBullbarFront","DisplayCategory","Mech");
TweakItem("Base.89BroncoBumperRear","DisplayCategory","Mech");
TweakItem("Base.89BroncoWindshield2","DisplayCategory","Mech");
TweakItem("Base.89BroncoWindowSide2","DisplayCategory","Mech");
TweakItem("Base.89BroncoWindowSideRear2","DisplayCategory","Mech");
TweakItem("Base.89BroncoWindshieldRear2","DisplayCategory","Mech");
TweakItem("Base.89BroncoBedCover","DisplayCategory","Mech");
TweakItem("Base.89BroncoBarrier","DisplayCategory","Mech");
end

--89trooper
--https://steamcommunity.com/sharedfiles/filedetails/?id=2932549988
if getActivatedMods():contains("89trooper") then
TweakItem("Base.89trooperTire2","DisplayCategory","Mech");
TweakItem("Base.89trooperTrunkSmall2","DisplayCategory","Mech");
TweakItem("Base.89trooperTrunkLarge2","DisplayCategory","Mech");
TweakItem("Base.89trooperRoofrack2","DisplayCategory","Mech");
TweakItem("Base.89trooperFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.89trooperRearDoor2","DisplayCategory","Mech");
TweakItem("Base.89trooperFrontDoorArmor","DisplayCategory","Mech");
TweakItem("Base.89trooperRearDoorArmor","DisplayCategory","Mech");
TweakItem("Base.89trooperWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.89trooperWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.89trooperBackWindowArmor","DisplayCategory","Mech");
TweakItem("Base.89trooperEngineDoor2","DisplayCategory","Mech");
TweakItem("Base.89trooperTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.89trooperSeatFront2","DisplayCategory","Mech");
TweakItem("Base.89trooperSeatRear2","DisplayCategory","Mech");
TweakItem("Base.89trooperBumperFront0","DisplayCategory","Mech");
TweakItem("Base.89trooperBullbarFrontA","DisplayCategory","Mech");
TweakItem("Base.89trooperBullbarFrontB","DisplayCategory","Mech");
TweakItem("Base.89trooperBumperRear0","DisplayCategory","Mech");
TweakItem("Base.89trooperWindshield2","DisplayCategory","Mech");
TweakItem("Base.89trooperSideWindow2","DisplayCategory","Mech");
TweakItem("Base.89trooperRearWindshield2","DisplayCategory","Mech");
TweakItem("Base.89trooperMudflaps2","DisplayCategory","Mech");
TweakItem("Base.89trooperSideSteps2","DisplayCategory","Mech");
end

--89Defender90
--https://steamcommunity.com/sharedfiles/filedetails/?id=2443275640
if getActivatedMods():contains("89def90") then
TweakItem("Base.def90SpareCompartment1","DisplayCategory","Mech");
TweakItem("Base.def90SpareCompartment2","DisplayCategory","Mech");
TweakItem("Base.def90SpareCompartment3","DisplayCategory","Mech");
end

--89Defender110
--https://steamcommunity.com/sharedfiles/filedetails/?id=2441990998
if getActivatedMods():contains("89def110") then
TweakItem("Base.def110SpareCompartment1","DisplayCategory","Mech");
TweakItem("Base.def110SpareCompartment2","DisplayCategory","Mech");
TweakItem("Base.def110SpareCompartment3","DisplayCategory","Mech");
end

--90fordF350ambulance
--https://steamcommunity.com/sharedfiles/filedetails/?id=2952802178
if getActivatedMods():contains("90fordF350ambulance") then
TweakItem("Base.90fordF350Tire2","DisplayCategory","Mech");
TweakItem("Base.90fordF350DoubleTires2","DisplayCategory","Mech");
TweakItem("Base.90fordF350Trunk2","DisplayCategory","Mech");
TweakItem("Base.90fordF350FrontDoor2","DisplayCategory","Mech");
TweakItem("Base.90fordF350RearDoor2","DisplayCategory","Mech");
TweakItem("Base.90fordF350BackDoors2","DisplayCategory","Mech");
TweakItem("Base.90fordF350EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.90fordF350LeftStorageLids2","DisplayCategory","Mech");
TweakItem("Base.90fordF350CornerStorageLids2","DisplayCategory","Mech");
TweakItem("Base.90fordF350RightStorageLid2","DisplayCategory","Mech");
TweakItem("Base.90fordF350BumperFront","DisplayCategory","Mech");
TweakItem("Base.90fordF350BullbarFront","DisplayCategory","Mech");
TweakItem("Base.90fordF350ReinforcedBumperFront","DisplayCategory","Mech");
TweakItem("Base.90fordF350BumperRear","DisplayCategory","Mech");
TweakItem("Base.90fordF350WindowFrontArmor","DisplayCategory","Mech");
TweakItem("Base.90fordF350WindowRearRightArmor","DisplayCategory","Mech");
TweakItem("Base.90fordF350WindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.90fordF350WindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.90fordF350SeatFront2","DisplayCategory","Mech");
TweakItem("Base.90fordF350SeatRear2","DisplayCategory","Mech");
TweakItem("Base.90fordF350ambulanceStretcher2","DisplayCategory","Mech");
TweakItem("Base.90fordF350Windshield2","DisplayCategory","Mech");
TweakItem("Base.90fordF350WindowFrontSide2","DisplayCategory","Mech");
TweakItem("Base.90fordF350WindowRearSide2","DisplayCategory","Mech");
TweakItem("Base.90fordF350WindowsBack2","DisplayCategory","Mech");
TweakItem("Base.90fordF350Sidesteps2","DisplayCategory","Mech");
end

--90pierceArrow
--https://steamcommunity.com/sharedfiles/filedetails/?id=2942793445
if getActivatedMods():contains("90pierceArrow") then
TweakItem("Base.90pierceArrowTire2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowDoubleTires2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowTrunk2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowRearDoor2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowSideWindowArmor","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowEngineDoor2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowTrunkDoorsLeft2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowTrunkDoorsRight2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowSeat2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowBumper0","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowReinforcedBumper1","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowWindshield2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowSideWindow2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowRearWindshield2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowMudflaps2","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowLadders","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowHoses","DisplayCategory","Mech");
TweakItem("Base.90pierceArrowWaterTank2","DisplayCategory","Mech");
end

--91range
--https://steamcommunity.com/sharedfiles/filedetails/?id=2409333430
if getActivatedMods():contains("91range") then
TweakItem("Base.91rangeTire2","DisplayCategory","Mech");
TweakItem("Base.91rangeTrunk2","DisplayCategory","Mech");
TweakItem("Base.91rangeRoofrack2","DisplayCategory","Mech");
TweakItem("Base.91rangeFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.91rangeRearDoor2","DisplayCategory","Mech");
TweakItem("Base.91rangeFrontWindowArmor","DisplayCategory","Mech");
TweakItem("Base.91rangeRearWindowArmor","DisplayCategory","Mech");
TweakItem("Base.91rangeWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.91rangeWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.91rangeEngineDoor2","DisplayCategory","Mech");
TweakItem("Base.91rangeTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.91rangeSeatFront2","DisplayCategory","Mech");
TweakItem("Base.91rangeSeatRear2","DisplayCategory","Mech");
TweakItem("Base.91rangeBumperFront0","DisplayCategory","Mech");
TweakItem("Base.91rangeBumperFront1","DisplayCategory","Mech");
TweakItem("Base.91rangeBullbarFrontA","DisplayCategory","Mech");
TweakItem("Base.91rangeBumperRear0","DisplayCategory","Mech");
TweakItem("Base.91rangeBullbarRearA","DisplayCategory","Mech");
TweakItem("Base.91rangeWindshield2","DisplayCategory","Mech");
TweakItem("Base.91rangeFrontSideWindow2","DisplayCategory","Mech");
TweakItem("Base.91rangeRearSideWindow2","DisplayCategory","Mech");
TweakItem("Base.91rangeRearWindshield2","DisplayCategory","Mech");
TweakItem("Base.91rangeSunRoof2","DisplayCategory","Mech");
TweakItem("Base.91rangeMudflaps2","DisplayCategory","Mech");
TweakItem("Base.91rangeSideSteps2","DisplayCategory","Mech");
TweakItem("Base.91rangeSnorkel2","DisplayCategory","Mech");
end

--92AMGeneralM998
--https://steamcommunity.com/sharedfiles/filedetails/?id=2642541073
if getActivatedMods():contains("92amgeneralM998") then
TweakItem("Base.V100Tire2","DisplayCategory","Mech");
TweakItem("Base.V101Tire2","DisplayCategory","Mech");
TweakItem("Base.M998Trunk2","DisplayCategory","Mech");
TweakItem("Base.M998Extra2","DisplayCategory","Mech");
TweakItem("Base.M998Roofrack1_Item","DisplayCategory","Mech");
TweakItem("Base.M998TrunkBarrier1_Item","DisplayCategory","Mech");
TweakItem("Base.M998TrunkBarrier2_Item","DisplayCategory","Mech");
TweakItem("Base.M998SpareMount_Item","DisplayCategory","Mech");
TweakItem("Base.M998SpareTireMount_Item","DisplayCategory","Mech");
TweakItem("Base.M998CarFrontDoor2","DisplayCategory","Mech");
TweakItem("Base.M998CarRearDoor2","DisplayCategory","Mech");
TweakItem("Base.M998CarFrontDoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M998CarRearDoorArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M998WindshieldArmor1_Item","DisplayCategory","Mech");
TweakItem("Base.M998WindshieldArmor2_Item","DisplayCategory","Mech");
TweakItem("Base.M998EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.M998TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.M998BackCover1_Item","DisplayCategory","Mech");
TweakItem("Base.M998CarSeat2","DisplayCategory","Mech");
TweakItem("Base.M998Muffler1_Item","DisplayCategory","Mech");
TweakItem("Base.M998Muffler2_Item","DisplayCategory","Mech");
TweakItem("Base.M998Bullbar1_Item","DisplayCategory","Mech");
TweakItem("Base.M998Bullbar2_Item","DisplayCategory","Mech");
TweakItem("Base.M998DefaultInterior2","DisplayCategory","Mech");
TweakItem("Base.M998Windshield2","DisplayCategory","Mech");
TweakItem("Base.M998SideWindow2","DisplayCategory","Mech");
TweakItem("Base.M998Mudflaps1_Item","DisplayCategory","Mech");
TweakItem("Base.M101A3Trunk2","DisplayCategory","Mech");
TweakItem("Base.M101A3Extra2","DisplayCategory","Mech");
TweakItem("Base.M101A3TrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.M101A3TrunkDoorTwo2","DisplayCategory","Mech");
TweakItem("Base.M101A3Cover1_Item","DisplayCategory","Mech");
TweakItem("Base.M101A3Tarp1_Item","DisplayCategory","Mech");
TweakItem("Base.leafSuspension2","DisplayCategory","Mech");
end

--92fordCVPI
--https://steamcommunity.com/sharedfiles/filedetails/?id=2962175696
if getActivatedMods():contains("92fordCVPI") then
TweakItem("Base.fordCVPITire1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPITrunk1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIFrontDoor1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIRearDoor1","DisplayCategory","Mech");
TweakItem("Base.fordCVPIWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.fordCVPIFrontWindowArmor","DisplayCategory","Mech");
TweakItem("Base.fordCVPIRearWindowArmor","DisplayCategory","Mech");
TweakItem("Base.fordCVPIWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIEngineDoor1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPITrunkDoor1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPISeatFront1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPISeatRear1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIBumperFront0","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIBumperFront1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIBumperRear0","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIWindshield1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIFrontSideWindow1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIRearSideWindow1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPIRearWindshield1","DisplayCategory","Mech");
TweakItem("Base.92fordCVPICabBarrier1","DisplayCategory","Mech");
end

--92nissanGTR
--https://steamcommunity.com/sharedfiles/filedetails/?id=2846036306
if getActivatedMods():contains("92nissanGTR") then
TweakItem("Base.R32Tire0","DisplayCategory","Mech");
TweakItem("Base.R32Tire1","DisplayCategory","Mech");
TweakItem("Base.R32Tire2","DisplayCategory","Mech");
TweakItem("Base.R32TireA","DisplayCategory","Mech");
TweakItem("Base.R32Trunk3","DisplayCategory","Mech");
TweakItem("Base.R32Door3","DisplayCategory","Mech");
TweakItem("Base.R32Bumper0","DisplayCategory","Mech");
TweakItem("Base.R32Bumper1","DisplayCategory","Mech");
TweakItem("Base.R32Bumper2","DisplayCategory","Mech");
TweakItem("Base.R32Bumper3","DisplayCategory","Mech");
TweakItem("Base.R32BumperA","DisplayCategory","Mech");
TweakItem("Base.R32BumperRear0","DisplayCategory","Mech");
TweakItem("Base.R32BumperRear1","DisplayCategory","Mech");
TweakItem("Base.R32BumperRear2","DisplayCategory","Mech");
TweakItem("Base.R32BumperRear3","DisplayCategory","Mech");
TweakItem("Base.R32BumperRearA","DisplayCategory","Mech");
TweakItem("Base.R32Sideskirts1","DisplayCategory","Mech");
TweakItem("Base.R32Sideskirts2","DisplayCategory","Mech");
TweakItem("Base.R32Sideskirts3","DisplayCategory","Mech");
TweakItem("Base.R32SideskirtsA","DisplayCategory","Mech");
TweakItem("Base.R32Spoiler0","DisplayCategory","Mech");
TweakItem("Base.R32Spoiler1","DisplayCategory","Mech");
TweakItem("Base.R32Spoiler2","DisplayCategory","Mech");
TweakItem("Base.R32Spoiler3","DisplayCategory","Mech");
TweakItem("Base.R32EngineDoor0","DisplayCategory","Mech");
TweakItem("Base.R32TrunkDoor3","DisplayCategory","Mech");
TweakItem("Base.R32FrontSeat3","DisplayCategory","Mech");
TweakItem("Base.R32RearSeat3","DisplayCategory","Mech");
TweakItem("Base.R32muffler0","DisplayCategory","Mech");
TweakItem("Base.R32muffler1","DisplayCategory","Mech");
TweakItem("Base.R32Windshield3","DisplayCategory","Mech");
TweakItem("Base.R32WindshieldRear3","DisplayCategory","Mech");
TweakItem("Base.R32FrontSideWindow3","DisplayCategory","Mech");
TweakItem("Base.R32RearSideWindow3","DisplayCategory","Mech");
TweakItem("Base.R32DoorArmor","DisplayCategory","Mech");
TweakItem("Base.R32RearWindowArmor","DisplayCategory","Mech");
TweakItem("Base.R32WindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.R32WindshieldRearArmor","DisplayCategory","Mech");
end

--93fordElgin
--https://steamcommunity.com/sharedfiles/filedetails/?id=2969343830
if getActivatedMods():contains("93fordElgin") then
TweakItem("Base.93fordCF8000Tire2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000DoubleTires2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000Trunk2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000Door2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000Bumper0","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000EngineDoor2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000Seat2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000Windshield2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000SideWindow2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000RearWindshield2","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000Muffler0","DisplayCategory","Mech");
TweakItem("Base.93fordCF8000Brushes","DisplayCategory","Mech");
end

--93townCar
--https://steamcommunity.com/sharedfiles/filedetails/?id=2932547723
if getActivatedMods():contains("93townCar") then
TweakItem("Base.93townCarTire1","DisplayCategory","Mech");
TweakItem("Base.93townCarTrunkFloor1","DisplayCategory","Mech");
TweakItem("Base.93townCarTrunk1","DisplayCategory","Mech");
TweakItem("Base.93townCarMiniBar1","DisplayCategory","Mech");
TweakItem("Base.93townCarTrunkRack1","DisplayCategory","Mech");
TweakItem("Base.93townCarFrontDoor1","DisplayCategory","Mech");
TweakItem("Base.93townCarRearDoor1","DisplayCategory","Mech");
TweakItem("Base.93townCarFrontDoorArmor","DisplayCategory","Mech");
TweakItem("Base.93townCarRearDoorArmor","DisplayCategory","Mech");
TweakItem("Base.93townCarWindshieldArmorA","DisplayCategory","Mech");
TweakItem("Base.93townCarWindshieldArmorB","DisplayCategory","Mech");
TweakItem("Base.93townCarWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.93townCarMiddleWindowArmor","DisplayCategory","Mech");
TweakItem("Base.93townCarEngineDoor1","DisplayCategory","Mech");
TweakItem("Base.93townCarTrunkDoor1","DisplayCategory","Mech");
TweakItem("Base.93townCarSeatFront1","DisplayCategory","Mech");
TweakItem("Base.93townCarSeatRear1","DisplayCategory","Mech");
TweakItem("Base.93townCarBumperFront0","DisplayCategory","Mech");
TweakItem("Base.93townCarBumperFront1","DisplayCategory","Mech");
TweakItem("Base.93townCarBullbarFrontA","DisplayCategory","Mech");
TweakItem("Base.93townCarBullbarFrontB","DisplayCategory","Mech");
TweakItem("Base.93townCarBullbarFrontC","DisplayCategory","Mech");
TweakItem("Base.93townCarBumperRear0","DisplayCategory","Mech");
TweakItem("Base.93townCarWindshield1","DisplayCategory","Mech");
TweakItem("Base.93townCarFrontSideWindow1","DisplayCategory","Mech");
TweakItem("Base.93townCarMiddleSideWindow1","DisplayCategory","Mech");
TweakItem("Base.93townCarRearSideWindow1","DisplayCategory","Mech");
TweakItem("Base.93townCarRearWindshield1","DisplayCategory","Mech");
TweakItem("Base.93townCarSunRoof1","DisplayCategory","Mech");
TweakItem("Base.BigBullHorns","DisplayCategory","Mech");
end

--97bushmaster
--https://steamcommunity.com/sharedfiles/filedetails/?id=2897390033
if getActivatedMods():contains("97bushmaster") then
TweakItem("Base.BushmasterTire","DisplayCategory","Mech");
TweakItem("Base.97BushmasterSeat","DisplayCategory","Mech");
TweakItem("Base.97BushmasterGunnerSeat","DisplayCategory","Mech");
TweakItem("Base.97BushLeftFender0","DisplayCategory","Mech");
TweakItem("Base.97BushRightFender0","DisplayCategory","Mech");
TweakItem("Base.97BushLeftStorage0","DisplayCategory","Mech");
TweakItem("Base.97BushRightStorage0","DisplayCategory","Mech");
TweakItem("Base.97BushRoofStorage0","DisplayCategory","Mech");
TweakItem("Base.97BushDoor2","DisplayCategory","Mech");
TweakItem("Base.97BushHatch2","DisplayCategory","Mech");
TweakItem("Base.97BushEngineDoor2","DisplayCategory","Mech");
TweakItem("Base.97BushStorageLidSmall","DisplayCategory","Mech");
TweakItem("Base.97BushStorageLidLarge","DisplayCategory","Mech");
TweakItem("Base.97BushWindshield2","DisplayCategory","Mech");
TweakItem("Base.97BushFrontSideWindow2","DisplayCategory","Mech");
TweakItem("Base.97BushSideWindow2","DisplayCategory","Mech");
TweakItem("Base.97BushWindshieldRear2","DisplayCategory","Mech");
TweakItem("Base.97BushMudflaps","DisplayCategory","Mech");
TweakItem("Base.97BushGasTank2","DisplayCategory","Mech");
TweakItem("Base.97BushBullbarSAS","DisplayCategory","Mech");
end

--99fordCVPI
--https://steamcommunity.com/sharedfiles/filedetails/?id=2971246021
if getActivatedMods():contains("99fordCVPI") then
TweakItem("Base.fordCVPITire1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPITrunk1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIFrontDoor1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIRearDoor1","DisplayCategory","Mech");
TweakItem("Base.fordCVPIWindshieldArmor","DisplayCategory","Mech");
TweakItem("Base.fordCVPIFrontWindowArmor","DisplayCategory","Mech");
TweakItem("Base.fordCVPIRearWindowArmor","DisplayCategory","Mech");
TweakItem("Base.fordCVPIWindshieldRearArmor","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIEngineDoor1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPITrunkDoor1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPISeatFront1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPISeatRear1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIBumperFront0","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIBumperFront1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIBumperRear0","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIWindshield1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIFrontSideWindow1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIRearSideWindow1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPIRearWindshield1","DisplayCategory","Mech");
TweakItem("Base.99fordCVPICabBarrier1","DisplayCategory","Mech");
end

--ISOContainers
--https://steamcommunity.com/sharedfiles/filedetails/?id=2625625421
if getActivatedMods():contains("isoContainers") then
TweakItem("Base.IsoContainerTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.IsoContainerDoubleTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.IsoContainerTankerTrunkDoor2","DisplayCategory","Mech");
TweakItem("Base.ISOHalfStorage2","DisplayCategory","Mech");
end
