--newcontainers
--https://steamcommunity.com/sharedfiles/filedetails/?id=2917951452
if getActivatedMods():contains("newcontainers") then
TweakItem("newcontainers.ammocan30","DisplayCategory","Cont");
TweakItem("newcontainers.ammocan50","DisplayCategory","Cont");
TweakItem("newcontainers.basket","DisplayCategory","Cont");
TweakItem("newcontainers.basket_forage","DisplayCategory","ClothBack");
TweakItem("newcontainers.canvastote","DisplayCategory","Cont");
TweakItem("newcontainers.cutleryroll","DisplayCategory","Cont");
TweakItem("newcontainers.foragepouch_front","DisplayCategory","ClothBag");
TweakItem("newcontainers.foragepouch_back","DisplayCategory","ClothBag");
TweakItem("newcontainers.jugempty","DisplayCategory","Cont");
TweakItem("newcontainers.roadsidekit","DisplayCategory","Cont");
TweakItem("newcontainers.shoppingbasket","DisplayCategory","Cont");
TweakItem("newcontainers.tacklebox","DisplayCategory","Cont");
TweakItem("newcontainers.ammocan","DisplayCategory","Cont");
TweakItem("newcontainers.cardboard_large","DisplayCategory","Cont");
TweakItem("newcontainers.cardboard_medium","DisplayCategory","Cont");
TweakItem("newcontainers.cardboard_small","DisplayCategory","Cont");
TweakItem("newcontainers.coffeecan","DisplayCategory","Cont");
TweakItem("newcontainers.coffeecan_open","DisplayCategory","Cont");
TweakItem("newcontainers.cookiejar","DisplayCategory","Cont");
TweakItem("newcontainers.donutbox","DisplayCategory","Cont");
TweakItem("newcontainers.fakerock","DisplayCategory","Cont");
TweakItem("newcontainers.jewelrybox","DisplayCategory","Cont");
TweakItem("newcontainers.kindlingbox","DisplayCategory","Cont");
TweakItem("newcontainers.lockbox","DisplayCategory","Cont");
TweakItem("newcontainers.piggybank","DisplayCategory","Cont");
TweakItem("newcontainers.pizzabox","DisplayCategory","Cont");
TweakItem("newcontainers.pizzaboxpw","DisplayCategory","Cont");
TweakItem("newcontainers.plastictote_large","DisplayCategory","Cont");
TweakItem("newcontainers.plastictote_medium","DisplayCategory","Cont");
TweakItem("newcontainers.plastictote_small","DisplayCategory","Cont");
TweakItem("newcontainers.shoebox","DisplayCategory","Cont");
TweakItem("newcontainers.spicerack","DisplayCategory","Cont");
TweakItem("newcontainers.tissuebox","DisplayCategory","Cont");
TweakItem("newcontainers.travelkit","DisplayCategory","Cont");
TweakItem("newcontainers.trunkorganizer","DisplayCategory","Cont");
TweakItem("newcontainers.cardboardbox","DisplayCategory","Cont");
TweakItem("newcontainers.carcrateb","DisplayCategory","Cont");
TweakItem("newcontainers.carcrateg","DisplayCategory","Cont");
TweakItem("newcontainers.carcrateo","DisplayCategory","Cont");
TweakItem("newcontainers.carcrater","DisplayCategory","Cont");
TweakItem("newcontainers.carcratey","DisplayCategory","Cont");
TweakItem("newcontainers.jugfull","DisplayCategory","FoodB");
end
