--newcontainers
--https://steamcommunity.com/sharedfiles/filedetails/?id=2917951452
if getActivatedMods():contains("newcontainers") then
TweakItem("newcontainers.ammocan30","DisplayCategory","Container");
TweakItem("newcontainers.ammocan50","DisplayCategory","Container");
TweakItem("newcontainers.basket","DisplayCategory","Container");
TweakItem("newcontainers.basket_forage","DisplayCategory","ClothB");
TweakItem("newcontainers.canvastote","DisplayCategory","Container");
TweakItem("newcontainers.cutleryroll","DisplayCategory","Container");
TweakItem("newcontainers.foragepouch_front","DisplayCategory","ClothB");
TweakItem("newcontainers.foragepouch_back","DisplayCategory","ClothB");
TweakItem("newcontainers.jugempty","DisplayCategory","Container");
TweakItem("newcontainers.roadsidekit","DisplayCategory","Container");
TweakItem("newcontainers.shoppingbasket","DisplayCategory","Container");
TweakItem("newcontainers.tacklebox","DisplayCategory","Container");
TweakItem("newcontainers.ammocan","DisplayCategory","Container");
TweakItem("newcontainers.cardboard_large","DisplayCategory","Container");
TweakItem("newcontainers.cardboard_medium","DisplayCategory","Container");
TweakItem("newcontainers.cardboard_small","DisplayCategory","Container");
TweakItem("newcontainers.coffeecan","DisplayCategory","Container");
TweakItem("newcontainers.coffeecan_open","DisplayCategory","Container");
TweakItem("newcontainers.cookiejar","DisplayCategory","Container");
TweakItem("newcontainers.donutbox","DisplayCategory","Container");
TweakItem("newcontainers.fakerock","DisplayCategory","Container");
TweakItem("newcontainers.jewelrybox","DisplayCategory","Container");
TweakItem("newcontainers.kindlingbox","DisplayCategory","Container");
TweakItem("newcontainers.lockbox","DisplayCategory","Container");
TweakItem("newcontainers.piggybank","DisplayCategory","Container");
TweakItem("newcontainers.pizzabox","DisplayCategory","Container");
TweakItem("newcontainers.pizzaboxpw","DisplayCategory","Container");
TweakItem("newcontainers.plastictote_large","DisplayCategory","Container");
TweakItem("newcontainers.plastictote_medium","DisplayCategory","Container");
TweakItem("newcontainers.plastictote_small","DisplayCategory","Container");
TweakItem("newcontainers.shoebox","DisplayCategory","Container");
TweakItem("newcontainers.spicerack","DisplayCategory","Container");
TweakItem("newcontainers.tissuebox","DisplayCategory","Container");
TweakItem("newcontainers.travelkit","DisplayCategory","Container");
TweakItem("newcontainers.trunkorganizer","DisplayCategory","Container");
TweakItem("newcontainers.cardboardbox","DisplayCategory","Container");
TweakItem("newcontainers.carcrateb","DisplayCategory","Container");
TweakItem("newcontainers.carcrateg","DisplayCategory","Container");
TweakItem("newcontainers.carcrateo","DisplayCategory","Container");
TweakItem("newcontainers.carcrater","DisplayCategory","Container");
TweakItem("newcontainers.carcratey","DisplayCategory","Container");
TweakItem("newcontainers.jugfull","DisplayCategory","FoodB");
end
