require("ItemTweaker_Copy_CC");

--PaintYourRide
--https://steamcommunity.com/sharedfiles/filedetails/?id=2281256511
if getActivatedMods():contains("PaintYourRide") then
TweakItem("PaintYourRide.VehiclePaintingMag1","DisplayCategory","LitR");
TweakItem("PaintYourRide.VehiclePaintingMag2","DisplayCategory","LitR");
TweakItem("PaintYourRide.SprayGun","DisplayCategory","Paint");
TweakItem("PaintYourRide.WireBrush","DisplayCategory","Paint");
TweakItem("PaintYourRide.CataloguePaintSpray","DisplayCategory","Paint");
TweakItem("PaintYourRide.CataloguePaintTints","DisplayCategory","Paint");
TweakItem("PaintYourRide.BoxAutomotivePaintTints","DisplayCategory","Paint");
TweakItem("PaintYourRide.BoxAutomotivePaintSprays1","DisplayCategory","Paint");
TweakItem("PaintYourRide.BoxAutomotivePaintSprays2","DisplayCategory","Paint");
TweakItem("PaintYourRide.BoxAutomotivePaintSprays3","DisplayCategory","Paint");
TweakItem("PaintYourRide.BoxAutomotivePaintSprays4","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotivePaintBucketEmpty","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotivePaintWhite","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotivePaintBottleEmpty","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveTintPaintBlack","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveTintPaintBlue","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveTintPaintCyan","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveTintPaintGreen","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveTintPaintMagenta","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveTintPaintRed","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveTintPaintYellow","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayCanEmpty","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPrimer","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintBlack","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintBlue","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintBlueNavy","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintBlueNeon","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintBlueOlympic","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintBrownDarkChocolate","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintBrownRusty","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintGreen","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintGreenArmy","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintGreenForest","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintGreenNeon","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintGrey","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintGreySteel","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintOrangeTangerine","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintPinkBubbleGum","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintPinkGlamorous","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintRed","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintRedBurgundy","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintRedCandyApple","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintVioletGrape","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintVioletIndigo","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintWhite","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintYellow","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintYellowNeon","DisplayCategory","Paint");
TweakItem("PaintYourRide.AutomotiveSprayPaintYellowTuscany","DisplayCategory","Paint");
end
