require("ItemTweaker_Copy_CC");

--SnakesModPack
--https://steamcommunity.com/sharedfiles/filedetails/?id=2719327441

--AliceBackpack5
if getActivatedMods():contains("AliceSPack") then
TweakItem("AliceBP.SpearMilitaryKnife","DisplayCategory","WepMelee");
TweakItem("AliceBP.SupportBackpack","DisplayCategory","ClothB");
-- TweakItem("AliceBP.MRE","DisplayCategory","FoodN");
-- TweakItem("AliceBP.BoxMRE","DisplayCategory","FoodN");
-- TweakItem("AliceBP.BoxMRE2","DisplayCategory","FoodN");
-- TweakItem("AliceBP.BoxMRE3","DisplayCategory","FoodN");
TweakItem("AliceBP.MilitiaPouch1","DisplayCategory","Container");
TweakItem("AliceBP.MilitiaPouch2","DisplayCategory","Container");
TweakItem("AliceBP.AlicePack","DisplayCategory","ClothB");
TweakItem("AliceBP.UpgradedAlicePack1","DisplayCategory","ClothB");
TweakItem("AliceBP.UpgradedAlicePack2","DisplayCategory","ClothB");
TweakItem("AliceBP.UpgradedAlicePack2b","DisplayCategory","ClothB");
TweakItem("AliceBP.UpgradedAlicePack3","DisplayCategory","ClothB");
TweakItem("AliceBP.UpgradedAlicePack3b","DisplayCategory","ClothB");
TweakItem("AliceBP.MilitaryCanteenEmpty","DisplayCategory","Container");
-- TweakItem("AliceBP.MilitaryCanteenFull","DisplayCategory","FoodB");
TweakItem("AliceBP.MilitaryKnife","DisplayCategory","WepMelee");
TweakItem("AliceBP.AlicePackUrban","DisplayCategory","ClothB");
TweakItem("AliceBP.AlicePackDesert","DisplayCategory","ClothB");
end

--AmmoMakerReloaded
if getActivatedMods():contains("AmmoMaker") then
TweakItem("Base.Tshirt_AmmoMakerGreen","DisplayCategory","Cloth");
TweakItem("AmmoMaker.ManualAM","DisplayCategory","LitR");
TweakItem("AmmoMaker.AMBookAReloading1","DisplayCategory","LitS");
TweakItem("AmmoMaker.AMBookAReloading2","DisplayCategory","LitS");
TweakItem("AmmoMaker.AMBookAReloading3","DisplayCategory","LitS");
TweakItem("AmmoMaker.AMBookAReloading4","DisplayCategory","LitS");
TweakItem("AmmoMaker.AMBookAReloading5","DisplayCategory","LitS");
TweakItem("AmmoMaker.WeaponsMagazine4","DisplayCategory","LitR");
TweakItem("AmmoMaker.SilencerAK","DisplayCategory","WepPart");
TweakItem("AmmoMaker.AKHG","DisplayCategory","WepPart");
TweakItem("AmmoMaker.AKRecoilPad","DisplayCategory","WepPart");
TweakItem("AmmoMaker.AKTacticalLight","DisplayCategory","WepPart");
TweakItem("AmmoMaker.AkIronSight2","DisplayCategory","WepPart");
TweakItem("AmmoMaker.AK47x4Scope","DisplayCategory","WepPart");
TweakItem("AmmoMaker.AK47MilitaryScope","DisplayCategory","WepPart");
TweakItem("AmmoMaker.Ammo_762x39mm","DisplayCategory","Ammo");
TweakItem("AmmoMaker.762x39mmBox","DisplayCategory","Ammo");
TweakItem("AmmoMaker.AKMMag","DisplayCategory","WepMag");
TweakItem("AmmoMaker.AK47","DisplayCategory","WepFire");
TweakItem("AmmoMaker.m16Part0","DisplayCategory","WepPart");
TweakItem("AmmoMaker.m16Part1","DisplayCategory","WepPart");
TweakItem("AmmoMaker.m16Part2","DisplayCategory","WepPart");
TweakItem("AmmoMaker.m16Part3","DisplayCategory","WepPart");
TweakItem("AmmoMaker.m16Part4","DisplayCategory","WepPart");
TweakItem("AmmoMaker.m16Part5","DisplayCategory","WepPart");
TweakItem("AmmoMaker.GunPowderBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.9mmCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.38Can","DisplayCategory","Ammo");
TweakItem("AmmoMaker.44Can","DisplayCategory","Ammo");
TweakItem("AmmoMaker.45Can","DisplayCategory","Ammo");
TweakItem("AmmoMaker.223Can","DisplayCategory","Ammo");
TweakItem("AmmoMaker.308Can","DisplayCategory","Ammo");
TweakItem("AmmoMaker.556x45mmCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.ShotgunShellsCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.762Can","DisplayCategory","Ammo");
TweakItem("AmmoMaker.9mmCasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.38CasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.44CasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.45CasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.223CasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.308CasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.556x45mmCasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.ShotgunShellsCasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.762x39mmCasesCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.9mmLeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.38LeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.44LeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.45LeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.223LeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.308LeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.556x45mmLeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.ShotgunShellsLeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.762x39mmLeadCan","DisplayCategory","Ammo");
TweakItem("AmmoMaker.Lead","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.LeadBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.MeltedLeadSaucepan","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.ReloadingToolBroken","DisplayCategory","Tool");
TweakItem("AmmoMaker.ReloadingTool","DisplayCategory","Tool");
TweakItem("AmmoMaker.AmmoPliers","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker2","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker3","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker4","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker5","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker6","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker7","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker8","DisplayCategory","Tool");
TweakItem("AmmoMaker.LeadMaker9","DisplayCategory","Tool");
TweakItem("AmmoMaker.9mmMold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.223Mold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.308Mold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.PelletsMold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.556Mold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.38Mold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.44Mold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.45Mold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.762Mold","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq9mm","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq223","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq308","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.CasqShotgun","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq556x45mm","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq38","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq44","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq45","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq762x39mm","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq9mmBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq223Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq308Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.CasqShotgunBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq556x45mmBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq38Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq44Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq45Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Casq762x39mmBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead9mm","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead223","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead308","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.LeadPellets","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead556x45mm","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead38","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead44","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead45","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead762x39mm","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead9mmBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead223Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead308Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.LeadPelletsBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead556x45mmBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead38Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead44Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead45Box","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.Lead762x39mmBox","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.GunPowderBottle","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.GunPowderBottleEmpty","DisplayCategory","CraftAmmo");
TweakItem("AmmoMaker.ToolPart1","DisplayCategory","Craft");
TweakItem("AmmoMaker.ToolPart2","DisplayCategory","Craft");
TweakItem("AmmoMaker.ToolPart3","DisplayCategory","Craft");
TweakItem("AmmoMaker.ToolPart4","DisplayCategory","Craft");
TweakItem("AmmoMaker.ToolPart5","DisplayCategory","Craft");
TweakItem("AmmoMaker.ToolBoxKit","DisplayCategory","Container");
TweakItem("AmmoMaker.AmmoBriefcase","DisplayCategory","Container");
TweakItem("AmmoMaker.AmmoMagazine1","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine2","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine3","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine6","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine7","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine8","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine9","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine10","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine11","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine12","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine13","DisplayCategory","LitR");
TweakItem("AmmoMaker.AmmoMagazine14","DisplayCategory","LitR");
end

--BatsMetalIconsRevived
if getActivatedMods():contains("BatesMetalicosRevived") then
TweakItem("BatesMetalicos.Bgrip","DisplayCategory","WepPart");
TweakItem("BatesMetalicos.Bsock","DisplayCategory","WepPart");
TweakItem("BatesMetalicos.MetalBaseballBat","DisplayCategory","WepMelee");
end

--FuelTanksMod
if getActivatedMods():contains("FuelTanksMod") then
TweakItem("FuelTanks.FuelTanksMag1","DisplayCategory","LitR");
TweakItem("FuelTanks.FuelMeter","DisplayCategory","Tool");
end

--MilitaryComplex
if getActivatedMods():contains("MilitaryComplex") then
TweakItem("Base.MilitaryComplexMap","DisplayCategory","Map");
end

--RiversideGunstore
if getActivatedMods():contains("Riverside Gunstore") then
TweakItem("Base.Shoes_BowlingTrainers","DisplayCategory","Cloth");
TweakItem("Base.Shoes_BowlingTrainersRed","DisplayCategory","Cloth");
TweakItem("Base.Shoes_BowlingTrainersGreen","DisplayCategory","Cloth");
TweakItem("Base.Bowlingball","DisplayCategory","WepMelee");
TweakItem("Base.BowlingPin","DisplayCategory","WepMelee");
end

--SkillsMag
if getActivatedMods():contains("SkillsMag") then
TweakItem("SkillMag.SkillMagPackage","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagSprint","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagLightFoot","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagNimble","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagSneaking","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagCarpentry","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagCooking","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagFarming","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagFirstAid","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagElectricity","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagMetal","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagFirearm","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagReloading","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagFishing","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagTrapping","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagForaging","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagMechanics","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagAxe","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagBlade","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagBlunt","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagSpear","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagMaintenance","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagTailor","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagAmmoReloading","DisplayCategory","LitS");
TweakItem("SkillMag.SkillMagHunting","DisplayCategory","LitS");
end

--SnakeClothingMod
if getActivatedMods():contains("SnakeClothingMod") then
TweakItem("Base.CowToy","DisplayCategory","Junk");
TweakItem("Base.SafeToy","DisplayCategory","Junk");
TweakItem("Base.HorseToy","DisplayCategory","Junk");
TweakItem("Base.Bag_BigSpiffoBackpack","DisplayCategory","ClothB");
TweakItem("Base.UpholsteryKit","DisplayCategory","CraftTailor");
TweakItem("Base.Bracelet_BangleRightBatman","DisplayCategory","ClothM");
TweakItem("Base.Bracelet_BangleLeftBatman","DisplayCategory","ClothM");
TweakItem("Base.Hat_Batman","DisplayCategory","Cloth");
TweakItem("Base.Boilersuit_Batman","DisplayCategory","Cloth");
TweakItem("Base.Gloves_Batman","DisplayCategory","Cloth");
TweakItem("Base.Tshirt_Batman","DisplayCategory","Cloth");
TweakItem("Base.TShirt_SportARGDECAL","DisplayCategory","Cloth");
TweakItem("Base.Tshirt_SportBarcDECAL","DisplayCategory","Cloth");
TweakItem("Base.Shorts_ShortSportBarc","DisplayCategory","Cloth");
TweakItem("Base.Shorts_ShortSportArg","DisplayCategory","Cloth");
TweakItem("Base.Socks_LongBarc","DisplayCategory","Cloth");
TweakItem("Base.Socks_LongArg","DisplayCategory","Cloth");
TweakItem("Base.Shoes_TrainerBarcelona","DisplayCategory","Cloth");
TweakItem("Base.Shoes_TrainerArgentina","DisplayCategory","Cloth");
TweakItem("Base.Hat_BarcelonaCap","DisplayCategory","Cloth");
TweakItem("Base.Hat_BarcelonaCap_Reverse","DisplayCategory","Cloth");
TweakItem("Base.DitoHoodieDOWN_WhiteTINT","DisplayCategory","Cloth");
TweakItem("Base.DitoHoodieUP_WhiteTINT","DisplayCategory","Cloth");
TweakItem("Base.AlicePackDito","DisplayCategory","ClothB");
end

--SnakeMansion
if getActivatedMods():contains("SnakeMansion") then
TweakItem("Base.RouletteStick","DisplayCategory","WepMelee");
TweakItem("Base.ZMChip1","DisplayCategory","Junk");
TweakItem("Base.ZMChip2","DisplayCategory","Junk");
TweakItem("Base.ZMChip3","DisplayCategory","Junk");
TweakItem("Base.ZMChip4","DisplayCategory","Junk");
TweakItem("Base.ZMChip5","DisplayCategory","Junk");
TweakItem("Base.ZMChip6","DisplayCategory","Junk");
TweakItem("Base.ZMChip7","DisplayCategory","Junk");
TweakItem("Base.ZMChip8","DisplayCategory","Junk");
TweakItem("Base.ZMChip9","DisplayCategory","Junk");
end

--TableSaw
if getActivatedMods():contains("TableSaw") then
TweakItem("ColorDyes.DyesMag","DisplayCategory","LitR");
TweakItem("ColorDyes.PlantRed","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantYellow","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantBlue","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantWhite","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantBlack","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantOrange","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantMagenta","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantGreen","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantBrown","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantCyan","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantTurquoise","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantPink","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantLightBrown","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantLightBlue","DisplayCategory","Paint");
TweakItem("ColorDyes.PlantGrey","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeBlack","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeWhite","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeBlue","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeYellow","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeRed","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeOrange","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeGreen","DisplayCategory","Paint");
TweakItem("ColorDyes.DyePurple","DisplayCategory","Paint");
TweakItem("ColorDyes.DyePink","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeCyan","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeBrown","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeLightBrown","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeLightBlue","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeTurquoise","DisplayCategory","Paint");
TweakItem("ColorDyes.DyeGrey","DisplayCategory","Paint");
TweakItem("ColorCrates.UniqueMag1","DisplayCategory","LitR");
TweakItem("ColorCrates.UniqueMag2","DisplayCategory","LitR");
TweakItem("ColorCrates.UniqueMag3","DisplayCategory","LitR");
TweakItem("ColorCrates.CrateBlue","DisplayCategory","Container");
TweakItem("ColorCrates.CrateGreen","DisplayCategory","Container");
TweakItem("ColorCrates.CrateLightBrown","DisplayCategory","Container");
TweakItem("ColorCrates.CrateLightBlue","DisplayCategory","Container");
TweakItem("ColorCrates.CrateBrown","DisplayCategory","Container");
TweakItem("ColorCrates.CrateOrange","DisplayCategory","Container");
TweakItem("ColorCrates.CrateCyan","DisplayCategory","Container");
TweakItem("ColorCrates.CratePink","DisplayCategory","Container");
TweakItem("ColorCrates.CrateGrey","DisplayCategory","Container");
TweakItem("ColorCrates.CrateTurquoise","DisplayCategory","Container");
TweakItem("ColorCrates.CratePurple","DisplayCategory","Container");
TweakItem("ColorCrates.CrateYellow","DisplayCategory","Container");
TweakItem("ColorCrates.CrateWhite","DisplayCategory","Container");
TweakItem("ColorCrates.CrateRed","DisplayCategory","Container");
TweakItem("ColorCrates.CrateBlack","DisplayCategory","Container");
TweakItem("ColorCrates.CrateAmmo","DisplayCategory","Container");
-- TweakItem("ColorCrates.CrateFood","DisplayCategory","Container");
TweakItem("ColorCrates.CrateLiterature","DisplayCategory","Container");
TweakItem("ColorCrates.CrateMedical","DisplayCategory","Container");
TweakItem("ColorCrates.CrateWeapons","DisplayCategory","Container");
TweakItem("ColorCrates.CrateCarpentry","DisplayCategory","Container");
TweakItem("ColorCrates.CrateElectricity","DisplayCategory","Container");
TweakItem("ColorCrates.CrateFarming","DisplayCategory","Container");
TweakItem("ColorCrates.CrateFishing","DisplayCategory","Container");
TweakItem("ColorCrates.CrateMechanics","DisplayCategory","Container");
TweakItem("ColorCrates.CrateMetalWelding","DisplayCategory","Container");
TweakItem("ColorCrates.CratePainting","DisplayCategory","Container");
TweakItem("ColorCrates.CrateScavenge","DisplayCategory","Container");
TweakItem("ColorCrates.CrateTrash","DisplayCategory","Container");
TweakItem("ColorCrates.CrateClothing","DisplayCategory","Container");
TweakItem("ColorCrates.BaseCrate","DisplayCategory","Container");
TweakItem("ColorCrates.CrateDito","DisplayCategory","Container");
TweakItem("ColorCrates.CrateArmy","DisplayCategory","Container");
TweakItem("ColorCrates.Crate9mm","DisplayCategory","Container");
TweakItem("ColorCrates.Crate45","DisplayCategory","Container");
TweakItem("ColorCrates.Crate38","DisplayCategory","Container");
TweakItem("ColorCrates.Crate44","DisplayCategory","Container");
TweakItem("ColorCrates.Crate223","DisplayCategory","Container");
TweakItem("ColorCrates.Crate308","DisplayCategory","Container");
TweakItem("ColorCrates.Crate556","DisplayCategory","Container");
TweakItem("ColorCrates.CrateShell","DisplayCategory","Container");
TweakItem("TableSaw.ClubSpikes","DisplayCategory","WepPart");
TweakItem("TableSaw.WoodenClub","DisplayCategory","WepMelee");
TweakItem("TableSaw.Turpentine","DisplayCategory","Craft");
TweakItem("TableSaw.Engine","DisplayCategory","Craft");
TweakItem("TableSaw.SawBlade","DisplayCategory","Craft");
TweakItem("TableSaw.BaseballSawBat","DisplayCategory","WepMelee");
TweakItem("TableSaw.BaseballWireBat","DisplayCategory","WepMelee");
TweakItem("TableSaw.SawMag1","DisplayCategory","LitR");
TweakItem("TableSaw.StickStacks","DisplayCategory","CraftCarp");
TweakItem("TableSaw.PlankStacks1","DisplayCategory","CraftCarp");
TweakItem("TableSaw.PlankStacks2","DisplayCategory","CraftCarp");
TweakItem("TableSaw.PlankStacks3","DisplayCategory","CraftCarp");
end

--TallerMecanico
if getActivatedMods():contains("TallerMecanico") then
TweakItem("Base.BatteryCleaner","DisplayCategory","Tool");
TweakItem("Base.CarVanTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.CarStepVanTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.SportsCarTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.SUVTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.PickUpVanTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.PickUpTruckTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.CarOffRoadTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.ModernCar02TunningParts","DisplayCategory","Mechanics");
TweakItem("Base.ModernCarTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.CarTaxiTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.CarStationWagonTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.CarLuxuryTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.SmallCar02TunningParts","DisplayCategory","Mechanics");
TweakItem("Base.SmallCarTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.CarNormalTunningParts","DisplayCategory","Mechanics");
TweakItem("Base.TrailerTrunk1","DisplayCategory","Mechanics");
TweakItem("Base.TrailerTrunk2","DisplayCategory","Mechanics");
TweakItem("Base.TrailerTrunk3","DisplayCategory","Mechanics");
TweakItem("Base.GlassMag1","DisplayCategory","LitR");
TweakItem("Base.GlassGlue","DisplayCategory","Mechanics");
TweakItem("Base.BigGlassPanel","DisplayCategory","Mechanics");
TweakItem("Base.SmallGlassPanel","DisplayCategory","Mechanics");
TweakItem("Base.GlassCutter","DisplayCategory","Tool");
TweakItem("Base.TireRubber","DisplayCategory","Mechanics");
TweakItem("Base.TireGlue","DisplayCategory","Mechanics");
TweakItem("Base.PMRTire","DisplayCategory","Mechanics");
TweakItem("Base.CarRim","DisplayCategory","Mechanics");
TweakItem("Base.DismountedTire","DisplayCategory","Mechanics");
TweakItem("Base.SuspensionParts","DisplayCategory","Mechanics");
TweakItem("Base.BrakesParts","DisplayCategory","Mechanics");
TweakItem("Base.BrakesPartsBox","DisplayCategory","Mechanics");
TweakItem("Base.SuspensionPartsBag","DisplayCategory","Mechanics");
end

--WPA
if getActivatedMods():contains("WPA") then
TweakItem("WPA.SilencerRK","DisplayCategory","Tool");
TweakItem("WPA.SpongeTube","DisplayCategory","Tool");
TweakItem("WPA.WeaponsMagazine","DisplayCategory","LitR");
TweakItem("WPA.WeaponsMagazine2","DisplayCategory","LitR");
TweakItem("WPA.WeaponsMagazine3","DisplayCategory","LitR");
TweakItem("WPA.WeaponsMagazine4","DisplayCategory","LitR");
TweakItem("WPA.BlackBriefcase","DisplayCategory","Container");
TweakItem("WPA.MilitarySling","DisplayCategory","WepPart");
TweakItem("WPA.AkIronSight","DisplayCategory","WepPart");
TweakItem("WPA.M16TL","DisplayCategory","WepPart");
TweakItem("WPA.M16LaserLight","DisplayCategory","WepPart");
TweakItem("WPA.M16Laser","DisplayCategory","WepPart");
TweakItem("WPA.M16Grip","DisplayCategory","WepPart");
TweakItem("WPA.M16Reflex","DisplayCategory","WepPart");
TweakItem("WPA.M16x4Scope","DisplayCategory","WepPart");
TweakItem("WPA.Silencerm16","DisplayCategory","WepPart");
TweakItem("WPA.M16RecoilPad","DisplayCategory","WepPart");
TweakItem("WPA.M16HG","DisplayCategory","WepPart");
TweakItem("WPA.M16BoltCarrier","DisplayCategory","WepPart");
TweakItem("WPA.PistolPart0","DisplayCategory","Craft");
TweakItem("WPA.PistolPart1","DisplayCategory","Craft");
TweakItem("WPA.PistolPart2","DisplayCategory","Craft");
TweakItem("WPA.PistolPart3","DisplayCategory","Craft");
TweakItem("WPA.PistolPart4","DisplayCategory","Craft");
TweakItem("WPA.PistolPart5","DisplayCategory","Craft");
TweakItem("WPA.223Part0","DisplayCategory","Craft");
TweakItem("WPA.223Part1","DisplayCategory","Craft");
TweakItem("WPA.223Part2","DisplayCategory","Craft");
TweakItem("WPA.223Part3","DisplayCategory","Craft");
TweakItem("WPA.223Part4","DisplayCategory","Craft");
TweakItem("WPA.223Part5","DisplayCategory","Craft");
TweakItem("WPA.308Part0","DisplayCategory","Craft");
TweakItem("WPA.308Part1","DisplayCategory","Craft");
TweakItem("WPA.308Part2","DisplayCategory","Craft");
TweakItem("WPA.308Part3","DisplayCategory","Craft");
TweakItem("WPA.308Part4","DisplayCategory","Craft");
TweakItem("WPA.308Part5","DisplayCategory","Craft");
TweakItem("WPA.ShotPart0","DisplayCategory","Craft");
TweakItem("WPA.ShotPart1","DisplayCategory","Craft");
TweakItem("WPA.ShotPart2","DisplayCategory","Craft");
TweakItem("WPA.ShotPart3","DisplayCategory","Craft");
TweakItem("WPA.ShotPart4","DisplayCategory","Craft");
TweakItem("WPA.ShotPart5","DisplayCategory","Craft");
TweakItem("WPA.ShotPart6","DisplayCategory","Craft");
TweakItem("WPA.Silencer1","DisplayCategory","WepPart");
TweakItem("WPA.Silencer2","DisplayCategory","WepPart");
TweakItem("WPA.Supressor1","DisplayCategory","WepPart");
TweakItem("WPA.TacticalLight","DisplayCategory","WepPart");
TweakItem("WPA.PHeavyBarrel","DisplayCategory","WepPart");
TweakItem("WPA.Grip1","DisplayCategory","WepPart");
TweakItem("WPA.Grip2","DisplayCategory","WepPart");
TweakItem("WPA.Pistolx2Scope","DisplayCategory","WepPart");
TweakItem("WPA.Pistolx2Scope2","DisplayCategory","WepPart");
TweakItem("WPA.RecoilCompensator","DisplayCategory","WepPart");
TweakItem("WPA.LaserLight","DisplayCategory","WepPart");
TweakItem("WPA.Slide1","DisplayCategory","WepPart");
TweakItem("WPA.Bipod","DisplayCategory","WepPart");
TweakItem("WPA.x20Scope","DisplayCategory","WepPart");
TweakItem("WPA.x40Scope","DisplayCategory","WepPart");
TweakItem("WPA.StealthTacticalScope","DisplayCategory","WepPart");
TweakItem("WPA.StealthTacticalScope2","DisplayCategory","WepPart");
TweakItem("WPA.StraightPullBolt","DisplayCategory","WepPart");
TweakItem("WPA.RHeavyBarrel","DisplayCategory","WepPart");
TweakItem("WPA.PolymerStock","DisplayCategory","WepPart");
TweakItem("WPA.RRecoilCompensator","DisplayCategory","WepPart");
TweakItem("WPA.RecoilPad2","DisplayCategory","WepPart");
TweakItem("WPA.RecoilPad3","DisplayCategory","WepPart");
TweakItem("WPA.CheekRest","DisplayCategory","WepPart");
TweakItem("WPA.Silencer3","DisplayCategory","WepPart");
TweakItem("WPA.Silencer5","DisplayCategory","WepPart");
TweakItem("WPA.Silencer6","DisplayCategory","WepPart");
TweakItem("WPA.TacticalLight2","DisplayCategory","WepPart");
TweakItem("WPA.ShotgunLaser","DisplayCategory","WepPart");
TweakItem("WPA.TacticalLaserLight2","DisplayCategory","WepPart");
TweakItem("WPA.SRTPS","DisplayCategory","WepPart");
TweakItem("WPA.SRecoilCompensator","DisplayCategory","WepPart");
TweakItem("WPA.ShellHolderStock","DisplayCategory","WepPart");
TweakItem("WPA.ShotgunPolymerStock","DisplayCategory","WepPart");
TweakItem("WPA.FoldingStock","DisplayCategory","WepPart");
end
