require("ItemTweaker_Copy_CC");

--SWATPACKREDUX
--https://steamcommunity.com/sharedfiles/filedetails/?id=2091564445
if getActivatedMods():contains("Swatpack") then
TweakItem("Base.Hat_SWATNeck","DisplayCategory","ClothAcc");
TweakItem("Base.Hat_SwatGasMask","DisplayCategory","ClothHead");
TweakItem("Base.SwatElbowPads","DisplayCategory","ClothArm");
TweakItem("Base.SwatKneePads","DisplayCategory","ClothLeg");
TweakItem("Base.SwatShoulderPads","DisplayCategory","ClothArm");
TweakItem("Base.Trousers_Swat","DisplayCategory","ClothLeg");
TweakItem("Base.Shoes_RiotBoots","DisplayCategory","ClothFeet");
TweakItem("Base.Shoes_SwatBoots","DisplayCategory","ClothFeet");
TweakItem("Base.Gloves_SwatGloves","DisplayCategory","ClothArm");
TweakItem("Base.Gloves_RiotGloves","DisplayCategory","ClothArm");
TweakItem("Base.Hat_SwatHelmet","DisplayCategory","ClothHead");
TweakItem("Base.Vest_BulletSwat","DisplayCategory","ClothBody");
TweakItem("Base.Jacket_Swat","DisplayCategory","ClothBody");
TweakItem("Base.Glasses_SwatGoggles","DisplayCategory","ClothHead");
TweakItem("Base.Hat_Balaclava_Swat","DisplayCategory","ClothHead");
TweakItem("Base.Hat_PoliceRiotHelmet","DisplayCategory","ClothHead");
TweakItem("Base.Hat_SWATRiotHelmet","DisplayCategory","ClothHead");
TweakItem("Base.Hat_SWATRiotHelmet2","DisplayCategory","ClothHead");
TweakItem("Base.RiotArmorSuit","DisplayCategory","ClothBody");
TweakItem("Base.Hat_Antibombhelmet","DisplayCategory","ClothHead");
TweakItem("Base.AntibombSuit","DisplayCategory","ClothBody");
TweakItem("Base.AntibombSuitP2","DisplayCategory","ClothBody");
TweakItem("Base.SWATPouch","DisplayCategory","ClothBag");
TweakItem("Base.Bag_BigSwatBag","DisplayCategory","ClothBack");
TweakItem("Base.Bag_PoliceBag","DisplayCategory","ClothBack");
TweakItem("Base.RubberShells","DisplayCategory","Ammo");
TweakItem("Base.RubberShellsBox","DisplayCategory","Ammo");
TweakItem("Base.RiotShieldSwat","DisplayCategory","WepShield");
TweakItem("Base.RiotShieldPolice","DisplayCategory","WepShield");
TweakItem("Base.RiotShotgun","DisplayCategory","WepFire");
TweakItem("Base.Co2ShortRiotShotgun","DisplayCategory","WepFire");
TweakItem("Base.SwatMP5","DisplayCategory","WepFire");
TweakItem("Base.9mmMp5Clip","DisplayCategory","WepAmmoMag");
TweakItem("Base.SwatStunGrenade","DisplayCategory","WepBomb");
TweakItem("Base.SwatFragGrenade","DisplayCategory","WepBomb");
TweakItem("Base.SwatSmokeGrenade","DisplayCategory","WepBomb");
end
