require("ItemTweaker_Copy_CC");

--VFE
--https://steamcommunity.com/sharedfiles/filedetails/?id=2667899942
if getActivatedMods():contains("VFExpansion1") then
TweakItem("Base.x2Scope","DisplayCategory","WepPart");
TweakItem("Base.x4Scope","DisplayCategory","WepPart");
TweakItem("Base.x8Scope","DisplayCategory","WepPart");
TweakItem("Base.Sling","DisplayCategory","WepPart");
TweakItem("Base.RecoilPad","DisplayCategory","WepPart");
TweakItem("Base.Bipod","DisplayCategory","WepPart");
TweakItem("Base.RedDot","DisplayCategory","WepPart");
TweakItem("Base.ShellHolder","DisplayCategory","WepPart");
TweakItem("Base.Laser","DisplayCategory","WepPart");
TweakItem("Base.ChokeTubeFull","DisplayCategory","WepPart");
TweakItem("Base.ChokeTubeImproved","DisplayCategory","WepPart");
TweakItem("Base.IronSight","DisplayCategory","WepPart");
TweakItem("Base.FiberglassStock","DisplayCategory","WepPart");
TweakItem("Base.OilFilterSuppressor","DisplayCategory","WepPart");
TweakItem("Base.OilFilterSuppressor2","DisplayCategory","WepPart");
TweakItem("Base.AmmoStraps","DisplayCategory","WepPart");
TweakItem("Base.Coupled556","DisplayCategory","WepPart");
TweakItem("Base.Coupled762","DisplayCategory","WepPart");
TweakItem("Base.Shotgun","DisplayCategory","WepFire");
TweakItem("Base.ShotgunSawnoff","DisplayCategory","WepFire");
TweakItem("Base.ShotgunSawnoffNoStock","DisplayCategory","WepFire");
TweakItem("Base.DoubleBarrelShotgun","DisplayCategory","WepFire");
TweakItem("Base.DoubleBarrelShotgunSawnoff","DisplayCategory","WepFire");
TweakItem("Base.Spas12","DisplayCategory","WepFire");
TweakItem("Base.Spas12Folded","DisplayCategory","WepFire");
TweakItem("Base.AK47","DisplayCategory","WepFire");
TweakItem("Base.AK47Folded","DisplayCategory","WepFire");
TweakItem("Base.SKS","DisplayCategory","WepFire");
TweakItem("Base.1022","DisplayCategory","WepFire");
TweakItem("Base.Mini14","DisplayCategory","WepFire");
TweakItem("Base.Mini14Folded","DisplayCategory","WepFire");
TweakItem("Base.CAR15","DisplayCategory","WepFire");
TweakItem("Base.CAR15D","DisplayCategory","WepFire");
TweakItem("Base.AssaultRifle2","DisplayCategory","WepFire");
TweakItem("Base.AssaultRifle","DisplayCategory","WepFire");
TweakItem("Base.HuntingRifle","DisplayCategory","WepFire");
TweakItem("Base.VarmintRifle","DisplayCategory","WepFire");
TweakItem("Base.LeverRifle","DisplayCategory","WepFire");
TweakItem("Base.MP5","DisplayCategory","WepFire");
TweakItem("Base.MP5SD","DisplayCategory","WepFire");
TweakItem("Base.Tec9","DisplayCategory","WepFire");
TweakItem("Base.Pistol2","DisplayCategory","WepFire");
TweakItem("Base.Pistol","DisplayCategory","WepFire");
TweakItem("Base.Glock","DisplayCategory","WepFire");
TweakItem("Base.Revolver_Short","DisplayCategory","WepFire");
TweakItem("Base.Revolver_Long","DisplayCategory","WepFire");
TweakItem("Base.Pistol3","DisplayCategory","WepFire");
TweakItem("Base.Revolver","DisplayCategory","WepFire");
TweakItem("Base.P229","DisplayCategory","WepFire");
TweakItem("Base.FireKlean","DisplayCategory","Tool");
TweakItem("Base.CleaningKit","DisplayCategory","Tool");
TweakItem("Base.762Clip","DisplayCategory","WepAmmoMag");
TweakItem("Base.762Box","DisplayCategory","Ammo");
TweakItem("Base.762Bullets","DisplayCategory","Ammo");
TweakItem("Base.22Bullets","DisplayCategory","Ammo");
TweakItem("Base.22Box","DisplayCategory","Ammo");
TweakItem("Base.223Clip20","DisplayCategory","WepAmmoMag");
TweakItem("Base.22ClipRifle","DisplayCategory","WepAmmoMag");
TweakItem("Base.308Clip","DisplayCategory","WepAmmoMag");
TweakItem("Base.OilFilter","DisplayCategory","Tool");
TweakItem("Base.OilFilter2","DisplayCategory","Tool");
TweakItem("Base.9mmClip20","DisplayCategory","WepAmmoMag");
TweakItem("Base.9mmClip17","DisplayCategory","WepAmmoMag");
TweakItem("Base.9mmClip30","DisplayCategory","WepAmmoMag");
TweakItem("Base.9mmClip13","DisplayCategory","WepAmmoMag");
end

--VFES
--https://steamcommunity.com/sharedfiles/filedetails/?id=2893333090
if getActivatedMods():contains("VFExpansion2") then
TweakItem("Base.Mosin","DisplayCategory","WepFire");
TweakItem("Base.Saiga12","DisplayCategory","WepFire");
TweakItem("Base.SVD","DisplayCategory","WepFire");
TweakItem("Base.Galil","DisplayCategory","WepFire");
TweakItem("Base.UMP45","DisplayCategory","WepFire");
TweakItem("Base.Makarov","DisplayCategory","WepFire");
TweakItem("Base.USP45","DisplayCategory","WepFire");
TweakItem("Base.SV98","DisplayCategory","WepFire");
TweakItem("Base.M249","DisplayCategory","WepFire");
TweakItem("Base.PKM","DisplayCategory","WepFire");
TweakItem("Base.Vityaz","DisplayCategory","WepFire");
TweakItem("Base.HK416","DisplayCategory","WepFire");
TweakItem("Base.VSS","DisplayCategory","WepFire");
TweakItem("Base.SVT40","DisplayCategory","WepFire");
TweakItem("Base.MP153","DisplayCategory","WepFire");
TweakItem("Base.MP153sawn","DisplayCategory","WepFire");
TweakItem("Base.762Clip10","DisplayCategory","WepAmmoMag");
TweakItem("Base.939Clip10","DisplayCategory","WepAmmoMag");
TweakItem("Base.556box100","DisplayCategory","WepAmmoMag");
TweakItem("Base.762box100","DisplayCategory","WepAmmoMag");
TweakItem("Base.12Clip5","DisplayCategory","WepAmmoMag");
TweakItem("Base.762Clip102","DisplayCategory","WepAmmoMag");
TweakItem("Base.762Clip103","DisplayCategory","WepAmmoMag");
TweakItem("Base.9mmClip8","DisplayCategory","WepAmmoMag");
TweakItem("Base.45Clip12","DisplayCategory","WepAmmoMag");
TweakItem("Base.45Clip25","DisplayCategory","WepAmmoMag");
TweakItem("Base.9mmClip302","DisplayCategory","WepAmmoMag");
end