require("ItemTweaker_Copy_CC");

--ZombieVirusVaccine
--https://steamcommunity.com/sharedfiles/filedetails/?id=2512119000
if getActivatedMods():contains("DemoniusZombieVirusVaccine") 
or getActivatedMods():contains("VaccinDrReapers") 
or getActivatedMods():contains("VaccinDrReapersMP") 
then
TweakItem("LabBooks.BkLaboratoryEquipment1","DisplayCategory","LitR");
TweakItem("LabBooks.BkVirologyCourses1","DisplayCategory","LitR");
TweakItem("LabBooks.BkChemistryCourse","DisplayCategory","LitR");
TweakItem("LabItems.LabMicroscope","DisplayCategory","Tool");
TweakItem("LabItems.LabChromatograph","DisplayCategory","Tool");
TweakItem("LabItems.LabSpectrometer","DisplayCategory","Tool");
TweakItem("LabItems.LabChemistrySet","DisplayCategory","Tool");
TweakItem("LabItems.LabCentrifuge","DisplayCategory","Tool");
TweakItem("LabItems.LabMuffleFurnace","DisplayCategory","Tool");
TweakItem("LabItems.LabWorkbench","DisplayCategory","Tool");
TweakItem("LabItems.LabEasel","DisplayCategory","Tool");
TweakItem("LabItems.LabDecorSkeleton","DisplayCategory","Tool");
TweakItem("LabItems.LabDecorVirusModel","DisplayCategory","Tool");
TweakItem("LabItems.LabDecorCaduceus","DisplayCategory","Tool");
TweakItem("LabItems.LabDecorWhiteboard","DisplayCategory","Tool");
TweakItem("LabItems.LabPosterPeriodicTable","DisplayCategory","Tool");
TweakItem("LabItems.LabPosterSexyNurse","DisplayCategory","Tool");
TweakItem("LabItems.LabPosterWashHands","DisplayCategory","Tool");
TweakItem("LabItems.LabPosterBiohazard","DisplayCategory","Tool");
TweakItem("LabItems.LabPosterHumanBrain","DisplayCategory","Tool");
TweakItem("LabItems.LabNeonSignPharmacy","DisplayCategory","Tool");
TweakItem("LabItems.LabNeonSignPizza","DisplayCategory","Tool");
TweakItem("LabItems.Mov_Morge1","DisplayCategory","Tool");
TweakItem("LabItems.Mov_Morge2","DisplayCategory","Tool");
TweakItem("LabItems.LabSyringe","DisplayCategory","Tool");
TweakItem("LabItems.LabSyringeReusable","DisplayCategory","Tool");
TweakItem("LabItems.LabSyringeReusableUsed","DisplayCategory","Tool");
TweakItem("LabItems.LabSyringePack","DisplayCategory","Tool");
TweakItem("LabItems.LabSyringeUsed","DisplayCategory","Tool");
TweakItem("LabItems.LabTestTube","DisplayCategory","Tool");
TweakItem("LabItems.LabTestTubeDirty","DisplayCategory","Tool");
TweakItem("LabItems.LabFlask","DisplayCategory","Tool");
TweakItem("LabItems.LabFlaskWater","DisplayCategory","Tool");
TweakItem("LabItems.LabFlaskDirty","DisplayCategory","Tool");
TweakItem("LabItems.LabTestResultNegative","DisplayCategory","Tool");
TweakItem("LabItems.LabTestResultPositive","DisplayCategory","Tool");
TweakItem("LabItems.LabGarbageBagWithRemains","DisplayCategory","Tool");
TweakItem("LabItems.LabPlasticBagWithRemains","DisplayCategory","Tool");
TweakItem("LabItems.MatInfectedBlood","DisplayCategory","Craft");
TweakItem("LabItems.MatTaintedBlood","DisplayCategory","Craft");
TweakItem("LabItems.MatShatteredGlass","DisplayCategory","Craft");
TweakItem("LabItems.ChHydrochloricAcidCan","DisplayCategory","Craft");
TweakItem("LabItems.ChSodiumHydroxideBag","DisplayCategory","Craft");
TweakItem("LabItems.ChAmmonia","DisplayCategory","Craft");
TweakItem("LabItems.ChSulfuricAcidCan","DisplayCategory","Craft");
TweakItem("LabItems.CmpSyringeWithBlood","DisplayCategory","Craft");
TweakItem("LabItems.CmpSyringeReusableWithBlood","DisplayCategory","Craft");
TweakItem("LabItems.CmpSyringeWithTaintedBlood","DisplayCategory","Craft");
TweakItem("LabItems.CmpSyringeReusableWithTaintedBlood","DisplayCategory","Craft");
TweakItem("LabItems.CmpTestTubeWithInfectedBlood","DisplayCategory","Craft");
TweakItem("LabItems.CmpTestTubeWithTaintedBlood","DisplayCategory","Craft");
TweakItem("LabItems.CmpFlaskWithBloodCells","DisplayCategory","Craft");
TweakItem("LabItems.CmpFlaskWithBloodPlasma","DisplayCategory","Craft");
TweakItem("LabItems.CmpFlaskWithLeukocytes","DisplayCategory","Craft");
TweakItem("LabItems.CmpTestTubeWithAntibodies","DisplayCategory","Craft");
TweakItem("LabItems.CmpSyringeWithPlainVaccine","DisplayCategory","Med");
TweakItem("LabItems.CmpSyringeReusableWithPlainVaccine","DisplayCategory","Med");
TweakItem("LabItems.CmpSyringeWithQualityVaccine","DisplayCategory","Med");
TweakItem("LabItems.CmpSyringeReusableWithQualityVaccine","DisplayCategory","Med");
TweakItem("LabItems.CmpSyringeWithAdvancedVaccine","DisplayCategory","Med");
TweakItem("LabItems.CmpSyringeReusableWithAdvancedVaccine","DisplayCategory","Med");
TweakItem("LabItems.CmpSyringeWithCure","DisplayCategory","Med");
TweakItem("LabItems.CmpSyringeReusableWithCure","DisplayCategory","Med");
TweakItem("LabItems.CmpFlaskWithSodiumHypochlorite","DisplayCategory","Craft");
TweakItem("LabItems.CmpFlaskWithAmmoniumSulfate","DisplayCategory","Craft");
TweakItem("LabItems.CmpFlaskWithHydrogenPeroxide","DisplayCategory","Craft");
TweakItem("LabItems.CmpAlbuminPills","DisplayCategory","Med");
TweakItem("LabItems.CmpChlorineTablets","DisplayCategory","Tool");
TweakItem("LabItems.FrnIngotMold","DisplayCategory","Craft");
TweakItem("LabItems.FrnGolgNugget","DisplayCategory","Craft");
TweakItem("LabItems.FrnSilverNugget","DisplayCategory","Craft");
TweakItem("LabItems.FrnGolgIngot","DisplayCategory","Craft");
TweakItem("LabItems.FrnSilverIngot","DisplayCategory","Craft");
end
