require("ItemTweaker_Copy_CC");

--SKILL BOOKS
TweakItem("Base.BookCarpentry1","DisplayName","Carpentry Vol.1: Beginner");
TweakItem("Base.BookCarpentry2","DisplayName","Carpentry Vol.2: Intermediate");
TweakItem("Base.BookCarpentry3","DisplayName","Carpentry Vol.3: Advanced");
TweakItem("Base.BookCarpentry4","DisplayName","Carpentry Vol.4: Expert");
TweakItem("Base.BookCarpentry5","DisplayName","Carpentry Vol.5: Master");
TweakItem("Base.BookCooking1","DisplayName","Cooking Vol.1: Beginner");
TweakItem("Base.BookCooking2","DisplayName","Cooking Vol.2: Intermediate");
TweakItem("Base.BookCooking3","DisplayName","Cooking Vol.3: Advanced");
TweakItem("Base.BookCooking4","DisplayName","Cooking Vol.4: Expert");
TweakItem("Base.BookCooking5","DisplayName","Cooking Vol.5: Master");
TweakItem("Base.BookElectrician1","DisplayName","Electricity Vol.1: Beginner");
TweakItem("Base.BookElectrician2","DisplayName","Electricity Vol.2: Intermediate");
TweakItem("Base.BookElectrician3","DisplayName","Electricity Vol.3: Advanced");
TweakItem("Base.BookElectrician4","DisplayName","Electricity Vol.4: Expert");
TweakItem("Base.BookElectrician5","DisplayName","Electricity Vol.5: Master");
TweakItem("Base.BookFarming1","DisplayName","Farming Vol.1: Beginner");
TweakItem("Base.BookFarming2","DisplayName","Farming Vol.2: Intermediate");
TweakItem("Base.BookFarming3","DisplayName","Farming Vol.3: Advanced");
TweakItem("Base.BookFarming4","DisplayName","Farming Vol.4: Expert");
TweakItem("Base.BookFarming5","DisplayName","Farming Vol.5: Master");
TweakItem("Base.BookFishing1","DisplayName","Fishing Vol.1: Beginner");
TweakItem("Base.BookFishing2","DisplayName","Fishing Vol.2: Intermediate");
TweakItem("Base.BookFishing3","DisplayName","Fishing Vol.3: Advanced");
TweakItem("Base.BookFishing4","DisplayName","Fishing Vol.4: Expert");
TweakItem("Base.BookFishing5","DisplayName","Fishing Vol.5: Master");
TweakItem("Base.BookFirstAid1","DisplayName","FirstAid Vol.1: Beginner");
TweakItem("Base.BookFirstAid2","DisplayName","FirstAid Vol.2: Intermediate");
TweakItem("Base.BookFirstAid3","DisplayName","FirstAid Vol.3: Advanced");
TweakItem("Base.BookFirstAid4","DisplayName","FirstAid Vol.4: Expert");
TweakItem("Base.BookFirstAid5","DisplayName","FirstAid Vol.5: Master");
TweakItem("Base.BookForaging1","DisplayName","Foraging Vol.1: Beginner");
TweakItem("Base.BookForaging2","DisplayName","Foraging Vol.2: Intermediate");
TweakItem("Base.BookForaging3","DisplayName","Foraging Vol.3: Advanced");
TweakItem("Base.BookForaging4","DisplayName","Foraging Vol.4: Expert");
TweakItem("Base.BookForaging5","DisplayName","Foraging Vol.5: Master");
TweakItem("Base.BookMechanic1","DisplayName","Mechanics Vol.1: Beginner");
TweakItem("Base.BookMechanic2","DisplayName","Mechanics Vol.2: Intermediate");
TweakItem("Base.BookMechanic3","DisplayName","Mechanics Vol.3: Advanced");
TweakItem("Base.BookMechanic4","DisplayName","Mechanics Vol.4: Expert");
TweakItem("Base.BookMechanic5","DisplayName","Mechanics Vol.5: Master");
TweakItem("Base.BookMetalWelding1","DisplayName","Metalwork Vol.1: Beginner");
TweakItem("Base.BookMetalWelding2","DisplayName","Metalwork Vol.2: Intermediate");
TweakItem("Base.BookMetalWelding3","DisplayName","Metalwork Vol.3: Advanced");
TweakItem("Base.BookMetalWelding4","DisplayName","Metalwork Vol.4: Expert");
TweakItem("Base.BookMetalWelding5","DisplayName","Metalwork Vol.5: Master");
TweakItem("Base.BookBlacksmith1","DisplayName","Smithing Vol.1: Beginner");
TweakItem("Base.BookBlacksmith2","DisplayName","Smithing Vol.2: Intermediate");
TweakItem("Base.BookBlacksmith3","DisplayName","Smithing Vol.3: Advanced");
TweakItem("Base.BookBlacksmith4","DisplayName","Smithing Vol.4: Expert");
TweakItem("Base.BookBlacksmith5","DisplayName","Smithing Vol.5: Master");
TweakItem("Base.BookTrapping1","DisplayName","Trapping Vol.1: Beginner");
TweakItem("Base.BookTrapping2","DisplayName","Trapping Vol.2: Intermediate");
TweakItem("Base.BookTrapping3","DisplayName","Trapping Vol.3: Advanced");
TweakItem("Base.BookTrapping4","DisplayName","Trapping Vol.4: Expert");
TweakItem("Base.BookTrapping5","DisplayName","Trapping Vol.5: Master");
--SKILL MAGS
TweakItem("Radio.RadioMag1","DisplayName","Raidios USA Magazine Vol. 1");
TweakItem("Radio.RadioMag2","DisplayName","Raidios USA Magazine Vol. 2");
TweakItem("Radio.RadioMag3","DisplayName","Raidios USA Magazine Vol. 3");
TweakItem("Base.FishingMag1","DisplayName","Angler USA Magazine Vol. 1");
TweakItem("Base.FishingMag2","DisplayName","Angler USA Magazine Vol. 2");
TweakItem("Base.ElectronicsMag1","DisplayName","Electronics Magazine Vol. 1");
TweakItem("Base.ElectronicsMag2","DisplayName","Electronics Magazine Vol. 2");
TweakItem("Base.ElectronicsMag3","DisplayName","Electronics Magazine Vol. 3");
TweakItem("Base.ElectronicsMag4","DisplayName","How to Use Generators");
TweakItem("Base.ElectronicsMag5","DisplayName","Electronics Magazine Vol. 4");
TweakItem("Base.EngineerMagazine1","DisplayName","Engineer Magazine Vol. 1");
TweakItem("Base.EngineerMagazine2","DisplayName","Engineer Magazine Vol. 2");
TweakItem("Base.CookingMag1","DisplayName","Good Cooking Magazine Vol. 1");
TweakItem("Base.CookingMag2","DisplayName","Good Cooking Magazine Vol. 2");
TweakItem("Base.FarmingMag1","DisplayName","Farming Almanac");
TweakItem("Base.HuntingMag1","DisplayName","Hunter Magazine Vol. 1");
TweakItem("Base.HuntingMag2","DisplayName","Hunter Magazine Vol. 2");
TweakItem("Base.HuntingMag3","DisplayName","Hunter Magazine Vol. 3");
TweakItem("Base.MetalworkMag1","DisplayName","Metalwork Magazine Vol. 1");
TweakItem("Base.MetalworkMag2","DisplayName","Metalwork Magazine Vol. 2");
TweakItem("Base.MetalworkMag3","DisplayName","Metalwork Magazine Vol. 3");
TweakItem("Base.MetalworkMag4","DisplayName","Metalwork Magazine Vol. 4");
TweakItem("Base.SmithingMag1","DisplayName","Smithing Magazine Vol. 1");
TweakItem("Base.SmithingMag2","DisplayName","Smithing Magazine Vol. 2");
TweakItem("Base.SmithingMag3","DisplayName","Smithing Magazine Vol. 3");
TweakItem("Base.SmithingMag4","DisplayName","Smithing Magazine Vol. 4");
TweakItem("Base.MechanicMag1","DisplayName","Laines Auto Vol. 1: Standard Models");
TweakItem("Base.MechanicMag2","DisplayName","Laines Auto Vol. 2: Commercial Models");
TweakItem("Base.MechanicMag3","DisplayName","Laines Auto Vol. 3: Performance Models");
--PAINT COLORS
TweakItem("Base.PaintBlack","DisplayName","Paint - Black");
TweakItem("Base.PaintBlue","DisplayName","Paint - Blue");
TweakItem("Base.PaintBrown","DisplayName","Paint - Brown");
TweakItem("Base.PaintCyan","DisplayName","Paint - Cyan");
TweakItem("Base.PaintGreen","DisplayName","Paint - Green");
TweakItem("Base.PaintGrey","DisplayName","Paint - Grey");
TweakItem("Base.PaintLightBlue","DisplayName","Paint - Light Blue");
TweakItem("Base.PaintLightBrown","DisplayName","Paint - Light Brown");
TweakItem("Base.PaintOrange","DisplayName","Paint - Orange");
TweakItem("Base.PaintPink","DisplayName","Paint - Pink");
TweakItem("Base.PaintPurple","DisplayName","Paint - Purple");
TweakItem("Base.PaintRed","DisplayName","Paint - Red");
TweakItem("Base.PaintTurquoise","DisplayName","Paint - Turquoise");
TweakItem("Base.PaintWhite","DisplayName","Paint - White");
TweakItem("Base.PaintYellow","DisplayName","Paint - Yellow");
--ELECTRONICS
TweakItem("Radio.TvAntique","DisplayName","Television - Antique");
TweakItem("Radio.TvWideScreen","DisplayName","Television - Premium Technologies");
TweakItem("Radio.TvBlack","DisplayName","Television - ValuTech");
TweakItem("Base.Radio","DisplayName","Radio");
TweakItem("Radio.RadioRed","DisplayName","Radio - Premium Technologies");
TweakItem("Radio.RadioBlack","DisplayName","Radio - ValuTech");
TweakItem("Radio.RadioMakeShift","DisplayName","Radio - Makeshift");
TweakItem("Radio.HamRadio1","DisplayName","Radio - HAM");
TweakItem("Radio.HamRadio2","DisplayName","Radio - Military");
TweakItem("Radio.HamRadioMakeShift","DisplayName","Radio - Makeshift HAM");
TweakItem("Radio.WalkieTalkie1","DisplayName","Walkie Talkie - Toys-R-Mine");
TweakItem("Radio.WalkieTalkie2","DisplayName","Walkie Talkie - ValuTech");
TweakItem("Radio.WalkieTalkie3","DisplayName","Walkie Talkie - Premium Technologies");
TweakItem("Radio.WalkieTalkie4","DisplayName","Walkie Talkie - Tactical");
TweakItem("Radio.WalkieTalkie5","DisplayName","Walkie Talkie - Military");
TweakItem("Radio.WalkieTalkieMakeShift","DisplayName","Walkie Talkie - Makeshift");
TweakItem("Base.LightBulbBlue","DisplayName","Light Bulb - Blue");
TweakItem("Base.LightBulbCyan","DisplayName","Light Bulb - Cyan");
TweakItem("Base.LightBulbGreen","DisplayName","Light Bulb - Green");
TweakItem("Base.LightBulb","DisplayName","Light Bulb - White");
TweakItem("Base.LightBulbMagenta","DisplayName","Light Bulb - Magenta");
TweakItem("Base.LightBulbOrange","DisplayName","Light Bulb - Orange");
TweakItem("Base.LightBulbPink","DisplayName","Light Bulb - Pink");
TweakItem("Base.LightBulbPurple","DisplayName","Light Bulb - Purple");
TweakItem("Base.LightBulbRed","DisplayName","Light Bulb - Red");
TweakItem("Base.LightBulbYellow","DisplayName","Light Bulb - Yellow");
--WRITING
TweakItem("Base.BluePen","DisplayName","Pen - Blue");
TweakItem("Base.RedPen","DisplayName","Pen - Red");
TweakItem("Base.Pen","DisplayName","Pen - Black");
--MATERIALS
TweakItem("Base.LogStacks4","DisplayName","Log Stack of Four");
TweakItem("Base.LogStacks3","DisplayName","Log Stack of Three");
TweakItem("Base.LogStacks2","DisplayName","Log Stack of Two");
