require("ItemTweaker_Copy_CC");

--BetterBelts
--https://steamcommunity.com/sharedfiles/filedetails/?id=2127583399
if getActivatedMods():contains("Better Belts") then
TweakItem("Base.Belt3","DisplayCategory","Cloth");
TweakItem("Base.Belt4","DisplayCategory","Cloth");
TweakItem("Base.HolsterSimpleL","DisplayCategory","ClothA");
TweakItem("Base.FirstAidKitB","DisplayCategory","ClothB");
TweakItem("Base.AFAK","DisplayCategory","Container");
TweakItem("Base.AFAKB","DisplayCategory","ClothB");
TweakItem("Base.ToolBoxB","DisplayCategory","ClothB");
TweakItem("Base.LunchboxB","DisplayCategory","ClothB");
TweakItem("Base.Lunchbox2B","DisplayCategory","ClothB");
TweakItem("Base.QuiverB","DisplayCategory","ClothA");
TweakItem("Base.PistolCase1B","DisplayCategory","ClothB");
TweakItem("Base.TentKitGreen","DisplayCategory","SurCamp");
TweakItem("Base.HookB","DisplayCategory","Craft");
TweakItem("Base.HookedWaterBottleEmptyOrange","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullOrange","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyYellow","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullYellow","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyGreen","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullGreen","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyPurple","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullPurple","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyRed","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullRed","DisplayCategory","FoodB");
TweakItem("Radio.CDplayer","DisplayCategory","Electronics");
end

--ScrapArmor
--https://steamcommunity.com/sharedfiles/filedetails/?id=2658619264
if getActivatedMods():contains("ScrapArmor(new version)") then
TweakItem("Base.Rucksack","DisplayCategory","ClothB");
TweakItem("Base.SwordSheath","DisplayCategory","ClothA");
TweakItem("Base.ScrapLegPouchL","DisplayCategory","ClothA");
TweakItem("Base.ScrapLegPouchR","DisplayCategory","ClothA");
TweakItem("SArmor.ArmorMag1","DisplayCategory","LitR");
TweakItem("SArmor.ArmorMag2","DisplayCategory","LitR");
TweakItem("SArmor.ArmorMag3","DisplayCategory","LitR");
TweakItem("SArmor.ArmorMag4","DisplayCategory","LitR");
TweakItem("SArmor.ArmorMag5","DisplayCategory","LitR");
TweakItem("Base.ScrapShield","DisplayCategory","WepShield");
TweakItem("Base.WoodenShield","DisplayCategory","WepShield");
TweakItem("Base.ScrapShieldPainted1","DisplayCategory","WepShield");
TweakItem("Base.ScrapShieldPainted2","DisplayCategory","WepShield");
TweakItem("Base.ScrapShieldPainted3","DisplayCategory","WepShield");
TweakItem("Base.CarDoorShield","DisplayCategory","WepShield");
TweakItem("Base.CarDoorShield1","DisplayCategory","WepShield");
TweakItem("Base.CarDoorShield2","DisplayCategory","WepShield");
TweakItem("Base.ScrapHandPlate2R","DisplayCategory","Cloth");
TweakItem("Base.ScrapHandPlate2L","DisplayCategory","Cloth");
TweakItem("Base.ScrapHandPlateR","DisplayCategory","Cloth");
TweakItem("Base.ScrapHandPlateL","DisplayCategory","Cloth");
TweakItem("Base.ScrapHandPlateStuddedR","DisplayCategory","Cloth");
TweakItem("Base.ScrapHandPlateStuddedL","DisplayCategory","Cloth");
TweakItem("Base.Hat_ScrapKettleHelmet","DisplayCategory","Cloth");
TweakItem("Base.Hat_ScrapHelmet","DisplayCategory","Cloth");
TweakItem("Base.Hat_ScrapHelmetopen","DisplayCategory","Cloth");
TweakItem("Base.Hat_MotorcycleHelmet2","DisplayCategory","Cloth");
TweakItem("Base.Hat_WelderMask2","DisplayCategory","Cloth");
TweakItem("Base.Hat_MotorcycleHelmet2open","DisplayCategory","Cloth");
TweakItem("Base.Hat_Rebreather","DisplayCategory","Cloth");
TweakItem("Base.ScrapKiltSign","DisplayCategory","Cloth");
TweakItem("Base.ScrapKiltPlated","DisplayCategory","Cloth");
TweakItem("Base.ScrapKiltStudded","DisplayCategory","Cloth");
TweakItem("Base.ScrapKilt","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadL","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadR","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadBoltsL","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadBoltsR","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadSign2L","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadSign2R","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadSignL","DisplayCategory","Cloth");
TweakItem("Base.ScrapLegPadSignR","DisplayCategory","Cloth");
TweakItem("Base.ScrapPauldrons","DisplayCategory","Cloth");
TweakItem("Base.ScrapPauldrons2","DisplayCategory","Cloth");
TweakItem("Base.ScrapPauldrons2Studded","DisplayCategory","Cloth");
TweakItem("Base.ScrapShinPlateR","DisplayCategory","Cloth");
TweakItem("Base.ScrapShinPlateL","DisplayCategory","Cloth");
TweakItem("Base.ScrapShinPlateStuddedR","DisplayCategory","Cloth");
TweakItem("Base.ScrapShinPlateStuddedL","DisplayCategory","Cloth");
TweakItem("Base.ScrapShinPlate2R","DisplayCategory","Cloth");
TweakItem("Base.ScrapShinPlate2L","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadL","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadR","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadSawL","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadSawR","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadBoltsL","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadBoltsR","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadSignL","DisplayCategory","Cloth");
TweakItem("Base.ScrapShoulderPadSignR","DisplayCategory","Cloth");
TweakItem("Base.ScrapVest","DisplayCategory","Cloth");
TweakItem("Base.ScrapVestPlated","DisplayCategory","Cloth");
TweakItem("Base.ScrapVestSign","DisplayCategory","Cloth");
TweakItem("Base.ScrapVestStudded","DisplayCategory","Cloth");
end

--ScrapGuns
--https://steamcommunity.com/sharedfiles/filedetails/?id=2125659488
if getActivatedMods():contains("ScrapGuns(new version)") then
TweakItem("SGuns.ScrapGunMag1","DisplayCategory","LitR");
TweakItem("SGuns.ScrapGunMag2","DisplayCategory","LitR");
TweakItem("SGuns.ScrapGunMag3","DisplayCategory","LitR");
TweakItem("SGuns.ScrapGunMag4","DisplayCategory","LitR");
TweakItem("SGuns.SSBox","DisplayCategory","Ammo");
TweakItem("SGuns.MetalScraps","DisplayCategory","Ammo");
TweakItem("SGuns.ShrapnelShell","DisplayCategory","Ammo");
TweakItem("SGuns.HRMagazine","DisplayCategory","WepAmmoMag");
TweakItem("SGuns.HPS","DisplayCategory","WepFire");
TweakItem("SGuns.HP","DisplayCategory","WepFire");
TweakItem("SGuns.HDBS","DisplayCategory","WepFire");
TweakItem("SGuns.HR","DisplayCategory","WepFire");
TweakItem("SGuns.HRB","DisplayCategory","WepFire");
TweakItem("SGuns.NailBomb","DisplayCategory","WepBomb");
TweakItem("SGuns.GlassBomb","DisplayCategory","WepBomb");
TweakItem("SGuns.HPB","DisplayCategory","WepBomb");
TweakItem("SGuns.HD","DisplayCategory","WepBomb");
TweakItem("SGuns.TBottle","DisplayCategory","WepRange");
TweakItem("SGuns.SlamFire","DisplayCategory","WepFire");
TweakItem("SGuns.SBBox","DisplayCategory","Ammo");
TweakItem("SGuns.SBullets","DisplayCategory","Ammo");
TweakItem("SGuns.SSMGMagazine","DisplayCategory","WepAmmoMag");
TweakItem("SGuns.SARBO","DisplayCategory","WepFire");
TweakItem("SGuns.SSMGUnfolded","DisplayCategory","WepFire");
TweakItem("SGuns.SSMGFolded","DisplayCategory","WepFire");
TweakItem("SGuns.SAR","DisplayCategory","WepFire");
TweakItem("SGuns.SARB","DisplayCategory","WepFire");
TweakItem("SGuns.SSR","DisplayCategory","WepFire");
TweakItem("SGuns.ScrapPistol","DisplayCategory","WepFire");
TweakItem("SGuns.ScrapSMG","DisplayCategory","WepFire");
TweakItem("SGuns.ScrapSMGMagazine","DisplayCategory","WepAmmoMag");
TweakItem("SGuns.ScrapPistolMagazine","DisplayCategory","WepAmmoMag");
TweakItem("SGuns.ScrapBullets","DisplayCategory","Ammo");
TweakItem("SGuns.ScrapBBox","DisplayCategory","Ammo");
TweakItem("SGuns.ScrapGatling","DisplayCategory","WepFire");
TweakItem("SGuns.GatlingBoxMagazine","DisplayCategory","WepAmmoMag");
end

--ScrapWeapons
--https://steamcommunity.com/sharedfiles/filedetails/?id=2122265954
if getActivatedMods():contains("ScrapWeapons(new version)") then
TweakItem("SWeapons.WeaponMag1","DisplayCategory","LitR");
TweakItem("SWeapons.WeaponMag2","DisplayCategory","LitR");
TweakItem("SWeapons.WeaponMag3","DisplayCategory","LitR");
TweakItem("SWeapons.WeaponMag4","DisplayCategory","LitR");
TweakItem("SWeapons.WeaponMag5","DisplayCategory","LitR");
TweakItem("SWeapons.WeaponMag6","DisplayCategory","LitR");
TweakItem("SWeapons.2x4","DisplayCategory","WepMelee");
TweakItem("SWeapons.2x4Can","DisplayCategory","WepMelee");
TweakItem("SWeapons.2x4Nail","DisplayCategory","WepMelee");
TweakItem("SWeapons.2x4Bolt","DisplayCategory","WepMelee");
TweakItem("SWeapons.2x4Scissors","DisplayCategory","WepMelee");
TweakItem("SWeapons.2x4Screwdriver","DisplayCategory","WepMelee");
TweakItem("SWeapons.2x4SScrewdriver","DisplayCategory","WepMelee");
TweakItem("SWeapons.ScrapPickaxe","DisplayCategory","WepMelee");
TweakItem("SWeapons.BigScrapPickaxe","DisplayCategory","WepMelee");
TweakItem("SWeapons.PipewithScissors","DisplayCategory","WepMelee");
TweakItem("SWeapons.TireIronAxe","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedPipeWrench","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedClimbingAxe","DisplayCategory","WepMelee");
TweakItem("SWeapons.SharpenedStopSign","DisplayCategory","WepMelee");
TweakItem("SWeapons.HugeScrapPickaxe","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedCrowbar","DisplayCategory","WepMelee");
TweakItem("SWeapons.BoltBat","DisplayCategory","WepMelee");
TweakItem("SWeapons.ChainBat","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedPipe","DisplayCategory","WepMelee");
TweakItem("SWeapons.TinCanClub","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedSledgehammer","DisplayCategory","WepMelee");
TweakItem("SWeapons.GearMace","DisplayCategory","WepMelee");
TweakItem("SWeapons.WireBat","DisplayCategory","WepMelee");
TweakItem("SWeapons.Micromaul","DisplayCategory","WepMelee");
TweakItem("SWeapons.ScrapSword","DisplayCategory","WepMelee");
TweakItem("SWeapons.ScrapMachete","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedNightstick","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedMachete","DisplayCategory","WepMelee");
TweakItem("SWeapons.ScrapBlade","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedBlade","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedCleaver","DisplayCategory","WepMelee");
TweakItem("SWeapons.SharpenedScrewdriver","DisplayCategory","WepMelee");
TweakItem("SWeapons.GlassShiv","DisplayCategory","WepMelee");
TweakItem("SWeapons.ScrapShiv","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedShiv","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedShivO","DisplayCategory","WepMelee");
TweakItem("SWeapons.ScrapClub","DisplayCategory","WepMelee");
TweakItem("SWeapons.SalvagedClub","DisplayCategory","WepMelee");
TweakItem("SWeapons.SpearSharpenedScrewdriver","DisplayCategory","WepMelee");
TweakItem("SWeapons.SpearScrapShiv","DisplayCategory","WepMelee");
TweakItem("SWeapons.SpearScrapMachete","DisplayCategory","WepMelee");
TweakItem("SWeapons.SpearSalvaged","DisplayCategory","WepMelee");
TweakItem("SWeapons.ScrapSpear","DisplayCategory","WepMelee");
end

--TheWorkshop
--https://steamcommunity.com/sharedfiles/filedetails/?id=2680473910
if getActivatedMods():contains("TheWorkshop(new version)") then
TweakItem("Base.Toolbelt","DisplayCategory","ClothA");
TweakItem("Base.NailGun","DisplayCategory","Tool");
TweakItem("Base.NailGunMagazine","DisplayCategory","Tool");
TweakItem("Base.CordlessDrill","DisplayCategory","Tool");
TweakItem("TW.WorkshopMag1","DisplayCategory","LitR");
TweakItem("TW.WorkshopMag2","DisplayCategory","LitR");
TweakItem("TW.WorkshopMag3","DisplayCategory","LitR");
TweakItem("TW.WorkshopMag4","DisplayCategory","LitR");
TweakItem("TW.WorkshopMag5","DisplayCategory","LitR");
TweakItem("TW.MetalPipeMold","DisplayCategory","CraftMetal");
TweakItem("TW.MetalBarMold","DisplayCategory","CraftMetal");
TweakItem("TW.SmallMetalSheetMold","DisplayCategory","CraftMetal");
TweakItem("TW.PropaneGasFurnace","DisplayCategory","Craft");
TweakItem("TW.GunParts","DisplayCategory","Craft");
TweakItem("TW.HugePropaneTank","DisplayCategory","Craft");
TweakItem("TW.LargePropaneTank","DisplayCategory","Craft");
TweakItem("TW.AirTank","DisplayCategory","Craft");
TweakItem("TW.MetalWorkbench","DisplayCategory","Craft");
TweakItem("TW.MetalParts","DisplayCategory","CraftMetal");
TweakItem("TW.BoxScrews","DisplayCategory","Craft");
TweakItem("TW.BoxLargeBolts","DisplayCategory","Craft");
TweakItem("TW.LargeBolt","DisplayCategory","Craft");
TweakItem("TW.Spring","DisplayCategory","Craft");
TweakItem("TW.Chain","DisplayCategory","Craft");
TweakItem("TW.Motor","DisplayCategory","Craft");
TweakItem("TW.File","DisplayCategory","Tool");
TweakItem("TW.Pliers","DisplayCategory","Tool");
TweakItem("TW.MetalCutter","DisplayCategory","Tool");
TweakItem("TW.GolfClubHead","DisplayCategory","Craft");
TweakItem("TW.HammerHead","DisplayCategory","Craft");
TweakItem("TW.SledgeHammerHead","DisplayCategory","Craft");
TweakItem("TW.AxeHead","DisplayCategory","Craft");
TweakItem("TW.SmallBlade","DisplayCategory","Craft");
TweakItem("TW.SmallMetalBar","DisplayCategory","Craft");
TweakItem("TW.MeatCleaverHead","DisplayCategory","Craft");
TweakItem("TW.ScytheHead","DisplayCategory","Craft");
TweakItem("TW.LongBlade","DisplayCategory","Craft");
TweakItem("TW.ShovelHead","DisplayCategory","Craft");
TweakItem("TW.HoeHead","DisplayCategory","Craft");
TweakItem("TW.PickaxeHead","DisplayCategory","Craft");
TweakItem("TW.RakeHead","DisplayCategory","Craft");
TweakItem("TW.ForkHead","DisplayCategory","Craft");
--New Categories for Base items
TweakItem("Base.LeadPipe","DisplayCategory","CraftMetal");
end
