require("ItemTweaker_Copy_CC");

--ImmersiveMedicine
--https://steamcommunity.com/sharedfiles/filedetails/?id=2709866494
if getActivatedMods():contains("iMeds") then
--CLOTHING
TweakItem("iMeds.BloodPressureMonitorLeft","DisplayCategory","Medical");
TweakItem("iMeds.BloodPressureMonitorRight","DisplayCategory","Medical");
TweakItem("iMeds.HeartRateMonitorLeft","DisplayCategory","Medical");
TweakItem("iMeds.HeartRateMonitorRight","DisplayCategory","Medical");
--BLOODBAG
TweakItem("iMeds.EmptyBloodBag","DisplayCategory","Medical");
TweakItem("iMeds.FullBloodBag","DisplayCategory","Medical");
TweakItem("iMeds.PeripheralVenousCatheter","DisplayCategory","Medical");
TweakItem("iMeds.BloodTestingKit","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagABN","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagABP","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagAN","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagAP","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagBN","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagBP","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagON","DisplayCategory","Medical");
TweakItem("iMeds.ErythrocyteSuspensionBagOP","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagABN","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagABP","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagAN","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagAP","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagBN","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagBP","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagON","DisplayCategory","Medical");
TweakItem("iMeds.PlasmaBagOP","DisplayCategory","Medical");
--DRUGS
TweakItem("iMeds.Alkagin","DisplayCategory","Drugs");
TweakItem("iMeds.AlkaginPack","DisplayCategory","Drugs");
TweakItem("iMeds.BismuthSubsalicylate","DisplayCategory","Drugs");
TweakItem("iMeds.BismuthSubsalicylatePack","DisplayCategory","Drugs");
TweakItem("iMeds.Butamirate","DisplayCategory","Drugs");
TweakItem("iMeds.ButamiratePack","DisplayCategory","Drugs");
TweakItem("iMeds.Erythropoietin","DisplayCategory","Drugs");
TweakItem("iMeds.ErythropoietinPack","DisplayCategory","Drugs");
TweakItem("iMeds.HemoStop","DisplayCategory","Drugs");
TweakItem("iMeds.HemoStopPack","DisplayCategory","Drugs");
TweakItem("iMeds.Morphine","DisplayCategory","Drugs");
TweakItem("iMeds.MorphinePack","DisplayCategory","Drugs");
TweakItem("iMeds.Naloxon","DisplayCategory","Drugs");
TweakItem("iMeds.NaloxonPack","DisplayCategory","Drugs");
TweakItem("iMeds.Nasivion","DisplayCategory","Drugs");
TweakItem("iMeds.NasivionPack","DisplayCategory","Drugs");
TweakItem("iMeds.Umifenovir","DisplayCategory","Drugs");
TweakItem("iMeds.UmifenovirPack","DisplayCategory","Drugs");
TweakItem("iMeds.UnknownPack","DisplayCategory","Drugs");
--OTHER
TweakItem("iMeds.Stethoscope","DisplayCategory","Medical");
--PROP
TweakItem("iMeds.BloodTester","DisplayCategory","Medical");
TweakItem("iMeds.BloodVolumeIncreaser","DisplayCategory","Medical");
TweakItem("iMeds.BloodVolumeReducer","DisplayCategory","Medical");
TweakItem("iMeds.DrugApplier","DisplayCategory","Medical");
TweakItem("iMeds.PulseChecker","DisplayCategory","Medical");
--SYRINGE
TweakItem("iMeds.SyringePack","DisplayCategory","Medical");
TweakItem("iMeds.Syringe","DisplayCategory","Medical");
TweakItem("iMeds.NeedlePack","DisplayCategory","Medical");
TweakItem("iMeds.Needle","DisplayCategory","Medical");
TweakItem("iMeds.SyringeWithNeedle","DisplayCategory","Medical");
TweakItem("iMeds.FullSyringeWithNeedle","DisplayCategory","Medical");
end
