require("ItemTweaker_Copy_CC");

--LastCallForAlcohol
--https://steamcommunity.com/sharedfiles/filedetails/?id=1997978868
if getActivatedMods():contains("LCFAV2") then
TweakItem("CCS.MoonshineFull","DisplayCategory","FoodA");
TweakItem("CCS.MoonshineEmpty","DisplayCategory","Container");
TweakItem("CCS.MoonshineBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.AbsintheFull","DisplayCategory","FoodA");
TweakItem("CCS.AbsintheEmpty","DisplayCategory","Container");
TweakItem("CCS.AbsintheWaterFull","DisplayCategory","FoodB");
TweakItem("CCS.Beer","DisplayCategory","FoodA");
TweakItem("CCS.BeerCanEmpty","DisplayCategory","Junk");
TweakItem("CCS.BeerCanSixPack","DisplayCategory","FoodA");
TweakItem("CCS.SojuFull","DisplayCategory","FoodA");
TweakItem("CCS.SojuEmpty","DisplayCategory","Container");
TweakItem("CCS.SojuWaterFull","DisplayCategory","FoodB");
TweakItem("CCS.SakeFull","DisplayCategory","FoodA");
TweakItem("CCS.SakeEmpty","DisplayCategory","Container");
TweakItem("CCS.SakeWaterFull","DisplayCategory","FoodB");
TweakItem("CCS.GinFull","DisplayCategory","FoodA");
TweakItem("CCS.GinEmpty","DisplayCategory","Container");
TweakItem("CCS.GinWaterFull","DisplayCategory","FoodB");
TweakItem("CCS.VodkaFull","DisplayCategory","FoodA");
TweakItem("CCS.VodkaEmpty","DisplayCategory","Container");
TweakItem("CCS.VodkaVodka","DisplayCategory","FoodB");
TweakItem("CCS.BourbonFull","DisplayCategory","FoodA");
TweakItem("CCS.BourbonEmpty","DisplayCategory","Container");
TweakItem("CCS.BourbonBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.BrandyFull","DisplayCategory","FoodA");
TweakItem("CCS.BrandyEmpty","DisplayCategory","Container");
TweakItem("CCS.BrandyBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.ChampangneFull","DisplayCategory","FoodA");
TweakItem("CCS.ChampangneEmpty","DisplayCategory","Container");
TweakItem("CCS.ChampangneBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.CognacFull","DisplayCategory","FoodA");
TweakItem("CCS.CognacEmpty","DisplayCategory","Container");
TweakItem("CCS.CognacBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.RumFull","DisplayCategory","FoodA");
TweakItem("CCS.RumEmpty","DisplayCategory","Container");
TweakItem("CCS.RumBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.TequilaFull","DisplayCategory","FoodA");
TweakItem("CCS.TequilaEmpty","DisplayCategory","Container");
TweakItem("CCS.TequilaBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.WhiskeyBlackLabelFull","DisplayCategory","FoodA");
TweakItem("CCS.WhiskeyBlackLabelEmpty","DisplayCategory","Container");
TweakItem("CCS.WhiskeyBlackLabelBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.WhiteWineFull","DisplayCategory","FoodA");
TweakItem("CCS.WhiteWineEmpty","DisplayCategory","Container");
TweakItem("CCS.WhiteWineBottleWater","DisplayCategory","FoodB");
TweakItem("CCS.DarkBeer","DisplayCategory","FoodA");
TweakItem("CCS.DarkBeerCanEmpty","DisplayCategory","Junk");
TweakItem("CCS.DarkBeerCanSixPack","DisplayCategory","FoodA");
TweakItem("CCS.TripleSecFull","DisplayCategory","FoodA");
TweakItem("CCS.TripleSecEmpty","DisplayCategory","Container");
TweakItem("CCS.TripleSecBottleWater","DisplayCategory","FoodB");
end
