require("ItemTweaker_Copy_CC");

--LittleYochisSkillbooks
--https://steamcommunity.com/sharedfiles/filedetails/?id=2737726733
if getActivatedMods():contains("LY_Skillbooks_agility")
or getActivatedMods():contains("LY_Skillbooks_firearms")
or getActivatedMods():contains("LY_Skillbooks_lockpicking")
or getActivatedMods():contains("LY_Skillbooks_melee")
or getActivatedMods():contains("LY_Skillbooks_passive") then

TweakItem("LY_Skillbooks.BookSprinting1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSprinting2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSprinting3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSprinting4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSprinting5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLightfooted1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLightfooted2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLightfooted3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLightfooted4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLightfooted5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookNimble1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookNimble2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookNimble3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookNimble4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookNimble5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSneaking1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSneaking2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSneaking3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSneaking4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSneaking5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAiming1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAiming2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAiming3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAiming4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAiming5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookReloading1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookReloading2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookReloading3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookReloading4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookReloading5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLockpicking1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLockpicking2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLockpicking3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLockpicking4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLockpicking5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAxe1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAxe2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAxe3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAxe4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookAxe5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookBlunt1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookBlunt2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookBlunt3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookBlunt4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookBlunt5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlunt1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlunt2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlunt3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlunt4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlunt5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLongBlade1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLongBlade2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLongBlade3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLongBlade4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookLongBlade5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlade1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlade2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlade3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlade4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSmallBlade5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSpear1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSpear2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSpear3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSpear4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookSpear5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookMaintenance1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookMaintenance2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookMaintenance3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookMaintenance4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookMaintenance5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookFitness1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookFitness2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookFitness3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookFitness4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookFitness5","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookStrength1","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookStrength2","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookStrength3","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookStrength4","DisplayCategory","LitS");
TweakItem("LY_Skillbooks.BookStrength5","DisplayCategory","LitS");
end
