require("ItemTweaker_Copy_CC");

--SWATPACKREDUX
--https://steamcommunity.com/sharedfiles/filedetails/?id=2091564445
if getActivatedMods():contains("Swatpack") then
TweakItem("Base.SWATPad","DisplayCategory","Cloth");
TweakItem("Base.SwatNeck","DisplayCategory","Cloth");
TweakItem("Base.Hat_SwatGasMask","DisplayCategory","Cloth");
TweakItem("Base.SwatElbowPads","DisplayCategory","Cloth");
TweakItem("Base.SwatKneePads","DisplayCategory","Cloth");
TweakItem("Base.Trousers_Swat","DisplayCategory","Cloth");
TweakItem("Base.Shoes_RiotBoots","DisplayCategory","Cloth");
TweakItem("Base.Shoes_SwatBoots","DisplayCategory","Cloth");
TweakItem("Base.Gloves_SwatGloves","DisplayCategory","Cloth");
TweakItem("Base.Gloves_RiotGloves","DisplayCategory","Cloth");
TweakItem("Base.Hat_SwatHelmet","DisplayCategory","Cloth");
TweakItem("Base.Vest_BulletSwat","DisplayCategory","Cloth");
TweakItem("Base.Jacket_Swat","DisplayCategory","Cloth");
TweakItem("Base.Glasses_SwatGoggles","DisplayCategory","Cloth");
TweakItem("Base.Hat_Balaclava_Swat","DisplayCategory","Cloth");
TweakItem("Base.Hat_PoliceRiotHelmet","DisplayCategory","Cloth");
TweakItem("Base.Hat_SWATRiotHelmet","DisplayCategory","Cloth");
TweakItem("Base.Hat_SWATRiotHelmet2","DisplayCategory","Cloth");
TweakItem("Base.RiotArmorSuit","DisplayCategory","Cloth");
TweakItem("Base.Hat_Antibombhelmet","DisplayCategory","Cloth");
TweakItem("Base.AntibombSuit","DisplayCategory","Cloth");
TweakItem("Base.AntibombSuitP2","DisplayCategory","Cloth");
TweakItem("Base.SWATPouch","DisplayCategory","ClothB");
TweakItem("Base.Bag_BigSwatBag","DisplayCategory","ClothB");
TweakItem("Base.Bag_PoliceBag","DisplayCategory","ClothB");
TweakItem("Base.RubberShells","DisplayCategory","Ammo");
TweakItem("Base.RubberShellsBox","DisplayCategory","Ammo");
TweakItem("Base.RiotShieldSwat","DisplayCategory","WepShield");
TweakItem("Base.RiotShieldPolice","DisplayCategory","WepShield");
TweakItem("Base.RiotShotgun","DisplayCategory","WepFire");
TweakItem("Base.Co2ShortRiotShotgun","DisplayCategory","WepFire");
TweakItem("Base.SwatMP5","DisplayCategory","WepFire");
TweakItem("Base.9mmMp5Clip","DisplayCategory","Ammo");
TweakItem("Base.SwatStunGrenade","DisplayCategory","WepBomb");
TweakItem("Base.SwatFragGrenade","DisplayCategory","WepBomb");
TweakItem("Base.SwatSmokeGrenade","DisplayCategory","WepBomb");
end
