require("ItemTweaker_Copy_CC");

--VILEM113APC
--https://steamcommunity.com/sharedfiles/filedetails/?id=1983277711
if getActivatedMods():contains("VileM113APC") then
TweakItem("Base.M113Tire1","DisplayCategory","Mechanics");
TweakItem("Base.M113Tire2","DisplayCategory","Mechanics");
TweakItem("Base.M113Tire3","DisplayCategory","Mechanics");
TweakItem("Base.OldM113Brake1","DisplayCategory","Mechanics");
TweakItem("Base.NormalM113Brake1","DisplayCategory","Mechanics");
TweakItem("Base.ModernM113Brake1","DisplayCategory","Mechanics");
TweakItem("Base.OldM113Brake2","DisplayCategory","Mechanics");
TweakItem("Base.NormalM113Brake2","DisplayCategory","Mechanics");
TweakItem("Base.ModernM113Brake2","DisplayCategory","Mechanics");
TweakItem("Base.OldM113Brake3","DisplayCategory","Mechanics");
TweakItem("Base.NormalM113Brake3","DisplayCategory","Mechanics");
TweakItem("Base.ModernM113Brake3","DisplayCategory","Mechanics");
TweakItem("Base.NormalM113Suspension1","DisplayCategory","Mechanics");
TweakItem("Base.ModernM113Suspension1","DisplayCategory","Mechanics");
TweakItem("Base.NormalM113Suspension2","DisplayCategory","Mechanics");
TweakItem("Base.ModernM113Suspension2","DisplayCategory","Mechanics");
TweakItem("Base.NormalM113Suspension3","DisplayCategory","Mechanics");
TweakItem("Base.ModernM113Suspension3","DisplayCategory","Mechanics");
TweakItem("Base.FrontM113Door1","DisplayCategory","Mechanics");
TweakItem("Base.RearM113Door1","DisplayCategory","Mechanics");
TweakItem("Base.FrontM113Door2","DisplayCategory","Mechanics");
TweakItem("Base.RearM113Door2","DisplayCategory","Mechanics");
TweakItem("Base.FrontM113Door3","DisplayCategory","Mechanics");
TweakItem("Base.RearM113Door3","DisplayCategory","Mechanics");
TweakItem("Base.EngineM113Door1","DisplayCategory","Mechanics");
TweakItem("Base.EngineM113Door2","DisplayCategory","Mechanics");
TweakItem("Base.EngineM113Door3","DisplayCategory","Mechanics");
TweakItem("Base.M113FrontWindow1","DisplayCategory","Mechanics");
TweakItem("Base.M113FrontWindow2","DisplayCategory","Mechanics");
TweakItem("Base.M113FrontWindow3","DisplayCategory","Mechanics");
TweakItem("Base.M113GloveBox1","DisplayCategory","Mechanics");
TweakItem("Base.M113GloveBox2","DisplayCategory","Mechanics");
TweakItem("Base.M113GloveBox3","DisplayCategory","Mechanics");
end
